// All website text, in English and Hindi. Scheme facts were checked against public
// sources (PIB, National Bee Board, FSSAI FoSCoS, GST portal) in September 2026.
// Guidelines change, so every scheme card points readers to the official portal.

export const content = {
  en: {
    lang: 'English',
    nav: { verify: 'Verify honey', how: 'How it works', schemes: 'Government schemes', honey: 'About honey', keeper: 'Keeper login', admin: 'Admin login' },
    hero: {
      cta: 'Verify a jar',
      scroll: 'Scroll to follow the honey',
      chapters: [
        { kicker: 'Honey Chain', title: 'From hive to home.', text: 'Every jar of honey has a story. We make it impossible to fake.' },
        { kicker: 'Smart hives', title: 'Hives you can see from anywhere.', text: 'Sensors track temperature, humidity, CO₂ and weight. AI flags problems before the colony suffers.' },
        { kicker: 'Verified by KVIC', title: 'Tested. Reviewed. Signed.', text: 'A laboratory tests the honey. A KVIC officer reviews it with AI support and signs it digitally. No signature, no packaging.' },
        { kicker: 'One scan', title: 'Scan. Trust. Enjoy.', text: 'Every jar carries a QR code linked to a tamper-evident blockchain record of its journey.' },
      ],
    },
    verify: {
      kicker: 'Consumer verification',
      title: 'Check your honey in seconds.',
      text: 'Type the batch number or the jar ID printed under the QR code, or scan the QR. No account needed.',
      placeholder: 'Batch number (HC-2026-0001) or jar ID (PB-2026-…-JAR-000001)',
      button: 'Verify',
      scan: 'Scan QR',
      scanning: 'Point the camera at the QR code',
      stopScan: 'Stop camera',
      noScan: 'Your browser cannot scan from this page. Open your phone camera, scan the QR, and it will open here.',
      checking: 'Checking the Honey Chain blockchain…',
      notFound: 'This code is not registered with Honey Chain. The jar may be counterfeit.',
      failed: 'Verification failed. Please try again.',
      another: 'Check another',
      sections: { product: 'Product', producer: 'Producer and origin', lab: 'Laboratory verification', approval: 'KVIC officer approval and digital certificate', history: 'Traceability history', chain: 'Supply chain journey' },
      labels: {
        product: 'Product', honeyType: 'Honey type', batch: 'Batch', harvested: 'Harvested', jar: 'Jar ID', bottles: 'Jars made from batch', quantity: 'Batch quantity',
        producer: 'Producer', origin: 'Origin', fssai: 'FSSAI licence', closed: 'Producer status', closedValue: 'Closed (records retained)',
        laboratory: 'Laboratory', certificate: 'Certificate', tested: 'Tested', moisture: 'Moisture', hmf: 'HMF', antibiotics: 'Antibiotic residue', notDetected: 'Not detected',
        approvedBy: 'Approved by', designation: 'Designation', signed: 'Signed', key: 'Signature key', block: 'block',
      },
      signatureValid: 'VERIFIED · digital signature valid',
      signatureInvalid: 'Signature could not be verified',
      noLab: 'No KVIC-verified laboratory certificate is on record.',
      noApproval: 'Not yet approved by a KVIC officer.',
      thisJar: 'this jar',
      chainOk: 'Blockchain check: intact',
      chainBad: 'Blockchain check: integrity problem detected',
      blocks: 'blocks',
      records: 'records',
      privacy: 'This page shows only public verification information. Private business data is never exposed.',
      verdicts: {
        VALID: { title: 'Verified authentic honey', reason: 'Laboratory-verified, officer-approved and recorded on the Honey Chain blockchain.' },
        NOT_CERTIFIED: { title: 'Not certified', reason: 'This honey has no KVIC-verified laboratory certificate on record.' },
        UNDER_REVIEW: { title: 'Under review: do not rely on this jar', reason: 'KVIC is reviewing this record. Do not rely on it until it is cleared.' },
        SUSPECTED_COPY: { title: 'Warning: this QR code may be copied', reason: 'The honey behind this code is genuine, but the code has been scanned in a way one real jar would not be. It may have been copied onto a fake jar. Check the seal and buy from the registered seller.' },
        COPY_CONFIRMED: { title: 'Fake jar: this QR code was copied', reason: 'KVIC has confirmed that this QR code was copied onto fake jars. Do not trust this jar. Return it to the seller and report it.' },
      },
      scans: {
        title: 'Scans of this QR code',
        summary: (scans, phones) => `Scanned ${scans} time${scans === 1 ? '' : 's'} on ${phones} phone${phones === 1 ? '' : 's'}.`,
        firstYou: 'You are the first person to scan this jar.',
        firstOther: (date) => `First scanned on ${date}, by someone else. If you just opened a new, sealed jar, that is a warning sign.`,
        explain: 'Each real jar has its own code. A code that turns up far apart within hours, or on many phones, has probably been printed onto fake jars.',
        alerts: 'Why this jar is flagged',
        reasons: {
          IMPOSSIBLE_TRAVEL: 'Scanned in two places too far apart for one jar to travel between the scans',
          MANY_PLACES: 'Scanned in many far-apart places by different phones',
          TOO_MANY_PHONES: 'Scanned by more phones than one jar is likely to meet',
          CONSUMER_REPORT: 'A buyer reported it as suspicious',
        },
        shareLocation: 'Share my approximate location to help catch copies',
        locationShared: 'Thank you. Your approximate location (about 1 km) was added to this scan.',
        locationDenied: 'Location was not shared. The check still works without it.',
        report: 'Report this jar',
        reportPrompt: 'What looks wrong? (seal broken, label photocopied, taste, bought from an unregistered seller...)',
        reportSend: 'Send report',
        reportThanks: 'Thank you. KVIC officers will look into this jar.',
        reportShort: 'Please write at least a few words.',
        privacy: 'We keep a random ID for this browser and, only if you allow it, a location rounded to about 1 km. No name or phone number.',
      },
      events: {
        HARVEST_RECORDED: 'Batch created at harvest', LAB_TEST_REQUESTED: 'Laboratory test requested', LAB_RESULT_SUBMITTED: 'Laboratory certificate submitted',
        LAB_RESULT_VERIFIED: 'Certificate verified and digitally signed by KVIC officer', LAB_RESULT_REJECTED: 'Certificate rejected by KVIC officer',
        PACK_BATCH_CREATED: 'Packaging batch created', PACK_CREATED: 'Jar registered and QR code generated', CUSTODY_TRANSFER: 'Custody transferred',
        PACK_FLAGGED_CLONED: 'KVIC confirmed this QR code was copied onto fake jars',
      },
      stages: { KEEPER: 'Keeper', WHOLESALER: 'Distributor / wholesaler', RETAILER: 'Retailer', CONSUMER: 'Consumer' },
      youScanned: 'You checked this honey',
    },
    how: {
      kicker: 'How it works',
      title: 'AI assists. KVIC authorizes. Blockchain records. QR verifies.',
      steps: [
        ['1', 'Keeper registers', 'A beekeeper registers with a KVIC / Madhukranti or parent-organisation number and an FSSAI licence. The regional KVIC officer reviews the credentials first.'],
        ['2', 'Smart hives', 'Sensors and AI watch the hive: temperature, humidity, CO₂, weight and risk indicators.'],
        ['3', 'Harvest and batch', 'Each harvest becomes a digital batch with its own identity on the blockchain.'],
        ['4', 'Lab and officer', 'A laboratory tests the batch. AI highlights unusual values. The regional officer decides and signs.'],
        ['5', 'Packaging and QR', 'Packaging unlocks only after verification. Every jar gets a unique QR, and the number of jars can never exceed the honey in the batch.'],
        ['6', 'Supply chain and you', 'Transfers to distributors and retailers are recorded. You scan the QR and see the whole journey.'],
      ],
    },
    who: {
      title: 'One platform, three ways in',
      items: [
        ['Beekeepers', 'Manage hives, harvests, lab requests, stock, orders, invoices and finance. Get AI hive-health and income forecasts. Sell with a verified QR.'],
        ['KVIC officers', 'Regional officers approve keepers and sign lab certificates. State officers see production and income. The KVIC Head supervises everything.'],
        ['Consumers', 'Scan a jar and see who made it, what the lab found and who signed it. No app, no account.'],
      ],
    },
    schemes: {
      kicker: 'Government schemes for honey and beekeeping',
      title: 'Support that exists for beekeepers.',
      note: 'Summaries are for orientation only. Eligibility, subsidy rates and dates change: always read the current guidelines on the official portal.',
      visit: 'Official website',
      items: [
        { name: 'National Beekeeping & Honey Mission (NBHM)', by: 'Ministry of Agriculture & Farmers Welfare · National Bee Board', text: 'A central sector scheme launched under Atmanirbhar Bharat with an outlay of ₹500 crore for FY 2020-21 to 2025-26. It supports training, bee colonies and equipment, processing, marketing and FPO-based institutions to raise honey production and beekeepers’ income.', link: 'https://nbb.gov.in' },
        { name: 'Madhukranti portal', by: 'National Bee Board (NBHM)', text: 'An online registration platform for beekeepers, beekeeping societies, firms and companies, built to trace the source of honey and other hive products and to reduce adulteration.', link: 'https://nbb.gov.in' },
        { name: 'KVIC Honey Mission', by: 'Khadi and Village Industries Commission', text: 'Launched in 2017 to modernise beekeeping: training in hive management, disease control and honey extraction, and distribution of bee boxes and extraction toolkits to rural beekeepers.', link: 'https://www.kvic.gov.in' },
        { name: 'PMEGP', by: 'Ministry of MSME · implemented by KVIC', text: 'Credit-linked subsidy scheme for new micro enterprises in manufacturing and services. Honey and beekeeping-based units can apply. Check the current project list and margin-money rules with KVIC.', link: 'https://www.kvic.gov.in' },
        { name: 'FSSAI licence and honey standards', by: 'Food Safety and Standards Authority of India', text: 'Food businesses, including honey producers and packers, need an FSSAI registration or licence through the FoSCoS portal. Honey must meet limits for moisture, sugars, HMF and residues.', link: 'https://foscos.fssai.gov.in' },
      ],
      closure: {
        title: 'Closing a honey business? Formal steps exist.',
        text: 'Surrender the FSSAI licence on FoSCoS, cancel GST registration (Form GST REG-16) and file the final return GSTR-10 within three months, withdraw with KVIC / Madhukranti or your parent organisation, and clear any scheme dues. Honey Chain records the closure formally through your regional officer.',
      },
    },
    honey: {
      kicker: 'About honey',
      title: 'Good to know about honey.',
      items: [
        ['What it is', 'Honey is made by bees from flower nectar. It is mostly natural sugars and about a fifth water, plus small amounts of enzymes, minerals and pollen.'],
        ['Varieties', 'The flowers the bees visit shape the colour and taste: wildflower, forest, multifloral, mustard, eucalyptus, litchi and many more across India.'],
        ['Why fake honey is hard to catch', 'Sugar-syrup adulteration can fool the eye and taste. Home tests such as the water or flame test are not reliable. Laboratory testing is, which is why Honey Chain puts a KVIC-verified certificate behind every jar.'],
        ['Crystallised honey is normal', 'Honey thickening or turning grainy over time is natural and does not mean it is fake. Warm the sealed jar gently in warm water to soften it.'],
        ['Storage', 'Keep it sealed, at room temperature, away from moisture and direct sun. Use a dry spoon.'],
        ['Not for infants', 'Do not give honey to babies under 12 months old.'],
      ],
    },
    footer: { line: 'Honey Chain is a prototype built for the Smart India Hackathon (problem statement 26021, Ministry of MSME).', keeperUrlNote: 'Keeper and Admin sign-in open the Honey Chain applications.' },
  },

  hi: {
    lang: 'हिन्दी',
    nav: { verify: 'शहद जाँचें', how: 'यह कैसे काम करता है', schemes: 'सरकारी योजनाएँ', honey: 'शहद के बारे में', keeper: 'कीपर लॉगिन', admin: 'एडमिन लॉगिन' },
    hero: {
      cta: 'जार जाँचें',
      scroll: 'शहद का सफ़र देखने के लिए स्क्रॉल करें',
      chapters: [
        { kicker: 'हनी चेन', title: 'छत्ते से आपके घर तक।', text: 'शहद के हर जार की एक कहानी होती है। हम उसे नकली बनाना असंभव कर देते हैं।' },
        { kicker: 'स्मार्ट छत्ते', title: 'कहीं से भी अपने छत्ते देखें।', text: 'सेंसर तापमान, नमी, CO₂ और वज़न पर नज़र रखते हैं। AI कॉलोनी को नुकसान होने से पहले समस्या बता देता है।' },
        { kicker: 'केवीआईसी द्वारा सत्यापित', title: 'जाँचा गया। परखा गया। हस्ताक्षरित।', text: 'प्रयोगशाला शहद की जाँच करती है। केवीआईसी अधिकारी AI की मदद से उसे परखकर डिजिटल हस्ताक्षर करते हैं। हस्ताक्षर नहीं, तो पैकेजिंग नहीं।' },
        { kicker: 'बस एक स्कैन', title: 'स्कैन करें। भरोसा करें।', text: 'हर जार पर एक क्यूआर कोड है, जो उसके सफ़र के छेड़छाड़-रोधी ब्लॉकचेन रिकॉर्ड से जुड़ा है।' },
      ],
    },
    verify: {
      kicker: 'उपभोक्ता सत्यापन',
      title: 'अपना शहद कुछ ही सेकंड में जाँचें।',
      text: 'बैच नंबर या क्यूआर कोड के नीचे छपा जार आईडी लिखें, या क्यूआर स्कैन करें। खाता बनाने की ज़रूरत नहीं।',
      placeholder: 'बैच नंबर (HC-2026-0001) या जार आईडी (PB-2026-…-JAR-000001)',
      button: 'जाँचें',
      scan: 'क्यूआर स्कैन करें',
      scanning: 'कैमरा क्यूआर कोड की ओर करें',
      stopScan: 'कैमरा बंद करें',
      noScan: 'आपका ब्राउज़र यहाँ स्कैन नहीं कर सकता। फ़ोन का कैमरा खोलकर क्यूआर स्कैन करें, वह यहीं खुलेगा।',
      checking: 'हनी चेन ब्लॉकचेन की जाँच हो रही है…',
      notFound: 'यह कोड हनी चेन में पंजीकृत नहीं है। जार नकली हो सकता है।',
      failed: 'सत्यापन विफल रहा। कृपया फिर कोशिश करें।',
      another: 'दूसरा जाँचें',
      sections: { product: 'उत्पाद', producer: 'उत्पादक और मूल स्थान', lab: 'प्रयोगशाला सत्यापन', approval: 'केवीआईसी अधिकारी की स्वीकृति और डिजिटल प्रमाणपत्र', history: 'ट्रेसेबिलिटी इतिहास', chain: 'आपूर्ति श्रृंखला का सफ़र' },
      labels: {
        product: 'उत्पाद', honeyType: 'शहद का प्रकार', batch: 'बैच', harvested: 'निकाला गया', jar: 'जार आईडी', bottles: 'इस बैच से बने जार', quantity: 'बैच की मात्रा',
        producer: 'उत्पादक', origin: 'मूल स्थान', fssai: 'एफएसएसएआई लाइसेंस', closed: 'उत्पादक की स्थिति', closedValue: 'बंद (रिकॉर्ड सुरक्षित)',
        laboratory: 'प्रयोगशाला', certificate: 'प्रमाणपत्र', tested: 'जाँच की तिथि', moisture: 'नमी', hmf: 'एचएमएफ', antibiotics: 'एंटीबायोटिक अवशेष', notDetected: 'नहीं मिला',
        approvedBy: 'स्वीकृति देने वाले', designation: 'पद', signed: 'हस्ताक्षर की तिथि', key: 'हस्ताक्षर कुंजी', block: 'ब्लॉक',
      },
      signatureValid: 'सत्यापित · डिजिटल हस्ताक्षर मान्य',
      signatureInvalid: 'हस्ताक्षर सत्यापित नहीं हो सका',
      noLab: 'केवीआईसी द्वारा सत्यापित कोई प्रयोगशाला प्रमाणपत्र दर्ज नहीं है।',
      noApproval: 'अभी तक केवीआईसी अधिकारी की स्वीकृति नहीं मिली।',
      thisJar: 'यह जार',
      chainOk: 'ब्लॉकचेन जाँच: सुरक्षित',
      chainBad: 'ब्लॉकचेन जाँच: गड़बड़ी पाई गई',
      blocks: 'ब्लॉक',
      records: 'रिकॉर्ड',
      privacy: 'यह पृष्ठ केवल सार्वजनिक सत्यापन जानकारी दिखाता है। निजी व्यावसायिक डेटा कभी उजागर नहीं होता।',
      verdicts: {
        VALID: { title: 'सत्यापित असली शहद', reason: 'प्रयोगशाला से सत्यापित, अधिकारी द्वारा स्वीकृत और हनी चेन ब्लॉकचेन पर दर्ज।' },
        NOT_CERTIFIED: { title: 'प्रमाणित नहीं', reason: 'इस शहद का केवीआईसी द्वारा सत्यापित कोई प्रयोगशाला प्रमाणपत्र दर्ज नहीं है।' },
        UNDER_REVIEW: { title: 'समीक्षाधीन: इस जार पर भरोसा न करें', reason: 'केवीआईसी इस रिकॉर्ड की समीक्षा कर रहा है। मंज़ूरी मिलने तक इस पर भरोसा न करें।' },
        SUSPECTED_COPY: { title: 'चेतावनी: यह क्यूआर कोड नकली हो सकता है', reason: 'इस कोड के पीछे का शहद असली है, पर यह कोड ऐसे स्कैन हुआ है जैसे एक असली जार के साथ नहीं होता। हो सकता है इसे नकली जार पर छापा गया हो। सील जाँचें और पंजीकृत विक्रेता से ही खरीदें।' },
        COPY_CONFIRMED: { title: 'नकली जार: यह क्यूआर कोड कॉपी किया गया है', reason: 'केवीआईसी ने पुष्टि की है कि यह क्यूआर कोड नकली जारों पर कॉपी किया गया। इस जार पर भरोसा न करें, इसे विक्रेता को लौटाएँ और शिकायत करें।' },
      },
      scans: {
        title: 'इस क्यूआर कोड के स्कैन',
        summary: (scans, phones) => `${phones} फ़ोन पर ${scans} बार स्कैन किया गया।`,
        firstYou: 'इस जार को सबसे पहले आपने स्कैन किया है।',
        firstOther: (date) => `पहली बार ${date} को किसी और ने स्कैन किया। अगर आपने अभी नया, सील बंद जार खोला है, तो यह चेतावनी का संकेत है।`,
        explain: 'हर असली जार का अपना कोड होता है। जो कोड कुछ ही घंटों में दूर-दूर या बहुत से फ़ोन पर दिखे, वह शायद नकली जारों पर छापा गया है।',
        alerts: 'यह जार क्यों चिह्नित है',
        reasons: {
          IMPOSSIBLE_TRAVEL: 'दो ऐसी जगहों पर स्कैन हुआ जो इतनी दूर हैं कि एक जार इतने समय में वहाँ नहीं पहुँच सकता',
          MANY_PLACES: 'अलग-अलग फ़ोन से कई दूर-दूर की जगहों पर स्कैन हुआ',
          TOO_MANY_PHONES: 'एक जार के हिसाब से बहुत ज़्यादा फ़ोन पर स्कैन हुआ',
          CONSUMER_REPORT: 'एक खरीदार ने इसे संदिग्ध बताया',
        },
        shareLocation: 'नकल पकड़ने में मदद के लिए मेरा अनुमानित स्थान साझा करें',
        locationShared: 'धन्यवाद। आपका अनुमानित स्थान (लगभग 1 किमी) इस स्कैन में जोड़ दिया गया।',
        locationDenied: 'स्थान साझा नहीं हुआ। जाँच इसके बिना भी काम करती है।',
        report: 'इस जार की शिकायत करें',
        reportPrompt: 'क्या गलत लग रहा है? (सील टूटी, लेबल फोटोकॉपी, स्वाद, अपंजीकृत विक्रेता से खरीदा...)',
        reportSend: 'शिकायत भेजें',
        reportThanks: 'धन्यवाद। केवीआईसी अधिकारी इस जार की जाँच करेंगे।',
        reportShort: 'कृपया कुछ शब्द लिखें।',
        privacy: 'हम इस ब्राउज़र की एक यादृच्छिक आईडी रखते हैं और, केवल आपकी अनुमति से, लगभग 1 किमी तक का स्थान। कोई नाम या फ़ोन नंबर नहीं।',
      },
      events: {
        HARVEST_RECORDED: 'शहद निकालने पर बैच बना', LAB_TEST_REQUESTED: 'प्रयोगशाला जाँच का अनुरोध', LAB_RESULT_SUBMITTED: 'प्रयोगशाला प्रमाणपत्र जमा हुआ',
        LAB_RESULT_VERIFIED: 'केवीआईसी अधिकारी ने प्रमाणपत्र सत्यापित कर डिजिटल हस्ताक्षर किए', LAB_RESULT_REJECTED: 'केवीआईसी अधिकारी ने प्रमाणपत्र अस्वीकार किया',
        PACK_BATCH_CREATED: 'पैकेजिंग बैच बना', PACK_CREATED: 'जार दर्ज हुआ और क्यूआर कोड बना', CUSTODY_TRANSFER: 'स्वामित्व हस्तांतरित हुआ',
        PACK_FLAGGED_CLONED: 'केवीआईसी ने पुष्टि की कि यह क्यूआर कोड नकली जारों पर कॉपी किया गया',
      },
      stages: { KEEPER: 'कीपर (मधुमक्खी पालक)', WHOLESALER: 'वितरक / थोक विक्रेता', RETAILER: 'खुदरा विक्रेता', CONSUMER: 'उपभोक्ता' },
      youScanned: 'आपने यह शहद जाँचा',
    },
    how: {
      kicker: 'यह कैसे काम करता है',
      title: 'AI सहायता करता है। केवीआईसी अधिकृत करता है। ब्लॉकचेन दर्ज करता है। क्यूआर सत्यापित करता है।',
      steps: [
        ['1', 'कीपर का पंजीकरण', 'मधुमक्खी पालक केवीआईसी / मधुक्रांति या मूल संस्था के नंबर और एफएसएसएआई लाइसेंस के साथ पंजीकरण करता है। पहले क्षेत्रीय केवीआईसी अधिकारी दस्तावेज़ों की जाँच करते हैं।'],
        ['2', 'स्मार्ट छत्ते', 'सेंसर और AI छत्ते पर नज़र रखते हैं: तापमान, नमी, CO₂, वज़न और जोखिम के संकेत।'],
        ['3', 'शहद निकालना और बैच', 'हर बार शहद निकालने पर एक डिजिटल बैच बनता है, जिसकी ब्लॉकचेन पर अपनी पहचान होती है।'],
        ['4', 'प्रयोगशाला और अधिकारी', 'प्रयोगशाला बैच की जाँच करती है। AI असामान्य मान बताता है। क्षेत्रीय अधिकारी निर्णय लेकर हस्ताक्षर करते हैं।'],
        ['5', 'पैकेजिंग और क्यूआर', 'सत्यापन के बाद ही पैकेजिंग खुलती है। हर जार को अलग क्यूआर मिलता है, और जार की संख्या बैच के शहद से ज़्यादा नहीं हो सकती।'],
        ['6', 'आपूर्ति श्रृंखला और आप', 'वितरकों और खुदरा विक्रेताओं तक हर हस्तांतरण दर्ज होता है। आप क्यूआर स्कैन कर पूरा सफ़र देखते हैं।'],
      ],
    },
    who: {
      title: 'एक प्लेटफ़ॉर्म, तीन रास्ते',
      items: [
        ['मधुमक्खी पालक', 'छत्ते, शहद निकालना, प्रयोगशाला अनुरोध, स्टॉक, ऑर्डर, चालान और वित्त संभालें। AI से छत्तों का स्वास्थ्य और आय का अनुमान पाएँ। सत्यापित क्यूआर के साथ बेचें।'],
        ['केवीआईसी अधिकारी', 'क्षेत्रीय अधिकारी कीपर को मंज़ूरी देते और प्रयोगशाला प्रमाणपत्रों पर हस्ताक्षर करते हैं। राज्य अधिकारी उत्पादन और आय देखते हैं। केवीआईसी प्रमुख सब कुछ देखते हैं।'],
        ['उपभोक्ता', 'जार स्कैन करें और देखें कि किसने बनाया, प्रयोगशाला ने क्या पाया और किसने हस्ताक्षर किए। न कोई ऐप, न कोई खाता।'],
      ],
    },
    schemes: {
      kicker: 'शहद और मधुमक्खी पालन के लिए सरकारी योजनाएँ',
      title: 'मधुमक्खी पालकों के लिए उपलब्ध सहायता।',
      note: 'ये सारांश केवल जानकारी के लिए हैं। पात्रता, सब्सिडी की दरें और तिथियाँ बदलती रहती हैं: हमेशा आधिकारिक पोर्टल पर वर्तमान दिशानिर्देश पढ़ें।',
      visit: 'आधिकारिक वेबसाइट',
      items: [
        { name: 'राष्ट्रीय मधुमक्खी पालन एवं शहद मिशन (एनबीएचएम)', by: 'कृषि एवं किसान कल्याण मंत्रालय · राष्ट्रीय मधुमक्खी बोर्ड', text: 'आत्मनिर्भर भारत के तहत शुरू की गई केंद्रीय क्षेत्र की योजना, जिसका वित्त वर्ष 2020-21 से 2025-26 तक ₹500 करोड़ का परिव्यय है। यह प्रशिक्षण, मधुमक्खी कॉलोनियों और उपकरणों, प्रसंस्करण, विपणन और एफपीओ-आधारित संस्थाओं के ज़रिये शहद उत्पादन और मधुमक्खी पालकों की आय बढ़ाने में मदद करती है।', link: 'https://nbb.gov.in' },
        { name: 'मधुक्रांति पोर्टल', by: 'राष्ट्रीय मधुमक्खी बोर्ड (एनबीएचएम)', text: 'मधुमक्खी पालकों, मधुमक्खी पालन समितियों, फ़र्मों और कंपनियों के ऑनलाइन पंजीकरण का मंच, जो शहद और छत्ते के अन्य उत्पादों का स्रोत पता लगाने और मिलावट घटाने के लिए बना है।', link: 'https://nbb.gov.in' },
        { name: 'केवीआईसी हनी मिशन', by: 'खादी और ग्रामोद्योग आयोग', text: '2017 में मधुमक्खी पालन के आधुनिकीकरण के लिए शुरू हुआ: छत्ता प्रबंधन, रोग नियंत्रण और शहद निष्कर्षण का प्रशिक्षण, तथा ग्रामीण मधुमक्खी पालकों को बी-बॉक्स और निष्कर्षण टूलकिट का वितरण।', link: 'https://www.kvic.gov.in' },
        { name: 'पीएमईजीपी', by: 'एमएसएमई मंत्रालय · केवीआईसी द्वारा क्रियान्वित', text: 'विनिर्माण और सेवा क्षेत्र की नई सूक्ष्म इकाइयों के लिए ऋण-आधारित सब्सिडी योजना। शहद और मधुमक्खी पालन आधारित इकाइयाँ आवेदन कर सकती हैं। वर्तमान परियोजना सूची और मार्जिन मनी के नियम केवीआईसी से देखें।', link: 'https://www.kvic.gov.in' },
        { name: 'एफएसएसएआई लाइसेंस और शहद के मानक', by: 'भारतीय खाद्य सुरक्षा एवं मानक प्राधिकरण', text: 'शहद उत्पादकों और पैकर सहित खाद्य व्यवसायों को FoSCoS पोर्टल से एफएसएसएआई पंजीकरण या लाइसेंस लेना होता है। शहद को नमी, शर्करा, एचएमएफ और अवशेषों की सीमाओं का पालन करना होता है।', link: 'https://foscos.fssai.gov.in' },
      ],
      closure: {
        title: 'शहद का व्यवसाय बंद कर रहे हैं? औपचारिक प्रक्रिया है।',
        text: 'FoSCoS पर एफएसएसएआई लाइसेंस सरेंडर करें, जीएसटी पंजीकरण रद्द करें (फ़ॉर्म GST REG-16) और तीन महीने के भीतर अंतिम रिटर्न GSTR-10 भरें, केवीआईसी / मधुक्रांति या अपनी मूल संस्था से पंजीकरण वापस लें, और योजनाओं की देनदारियाँ चुकाएँ। हनी चेन आपके क्षेत्रीय अधिकारी के माध्यम से बंदी को औपचारिक रूप से दर्ज करता है।',
      },
    },
    honey: {
      kicker: 'शहद के बारे में',
      title: 'शहद के बारे में जानने योग्य बातें।',
      items: [
        ['शहद क्या है', 'शहद मधुमक्खियाँ फूलों के रस से बनाती हैं। इसमें ज़्यादातर प्राकृतिक शर्करा और लगभग पाँचवाँ हिस्सा पानी होता है, साथ में थोड़े एंज़ाइम, खनिज और पराग।'],
        ['किस्में', 'मधुमक्खियाँ जिन फूलों पर जाती हैं, उनसे रंग और स्वाद तय होता है: जंगली फूल, वन, बहुपुष्पीय, सरसों, यूकेलिप्टस, लीची और भारत में और भी कई।'],
        ['नकली शहद पकड़ना मुश्किल क्यों है', 'चीनी की चाशनी की मिलावट आँख और स्वाद को धोखा दे सकती है। पानी या आग वाले घरेलू परीक्षण भरोसेमंद नहीं हैं। प्रयोगशाला जाँच भरोसेमंद है, इसीलिए हनी चेन हर जार के पीछे केवीआईसी-सत्यापित प्रमाणपत्र रखता है।'],
        ['जमा हुआ शहद सामान्य है', 'समय के साथ शहद का गाढ़ा या दानेदार होना स्वाभाविक है, इसका मतलब नकली होना नहीं है। बंद जार को गुनगुने पानी में रखकर नरम किया जा सकता है।'],
        ['भंडारण', 'इसे बंद, कमरे के तापमान पर, नमी और सीधी धूप से दूर रखें। सूखे चम्मच का उपयोग करें।'],
        ['शिशुओं के लिए नहीं', '12 महीने से छोटे बच्चों को शहद न दें।'],
      ],
    },
    footer: { line: 'हनी चेन स्मार्ट इंडिया हैकाथॉन (समस्या कथन 26021, एमएसएमई मंत्रालय) के लिए बनाया गया एक प्रोटोटाइप है।', keeperUrlNote: 'कीपर और एडमिन साइन-इन हनी चेन के एप्लिकेशन खोलते हैं।' },
  },
}
