import { sqlExec } from './connection.js'

// Timestamps stay TEXT in the same 'YYYY-MM-DD HH:MM:SS' (UTC) form SQLite produced, so every
// comparison and every date the apps already parse keeps working.
export const NOW_TEXT = "to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')"

// Turns the SQLite-flavoured table definitions used in this project into Postgres.
export function pgDdl(sql) {
  return sql
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/DATETIME DEFAULT CURRENT_TIMESTAMP/g, `TEXT DEFAULT (${NOW_TEXT})`)
    .replace(/\bREAL\b/g, 'DOUBLE PRECISION')
    .replace(/CREATE VIEW IF NOT EXISTS/g, 'CREATE OR REPLACE VIEW')
}

// Makes a table read-only for the ledger: no update, delete or truncate, ever.
export function immutable(table, message) {
  const trigger = `prevent_${table}_change`
  return `
    DROP TRIGGER IF EXISTS ${trigger} ON ${table};
    CREATE TRIGGER ${trigger} BEFORE UPDATE OR DELETE ON ${table}
      FOR EACH ROW EXECUTE FUNCTION forbid_change('${message}');
    DROP TRIGGER IF EXISTS ${trigger}_truncate ON ${table};
    CREATE TRIGGER ${trigger}_truncate BEFORE TRUNCATE ON ${table}
      FOR EACH STATEMENT EXECUTE FUNCTION forbid_change('${message}');
  `
}

export const FORBID_CHANGE = `
  CREATE OR REPLACE FUNCTION forbid_change() RETURNS trigger AS $$
  BEGIN
    RAISE EXCEPTION '%', TG_ARGV[0];
  END;
  $$ LANGUAGE plpgsql;
`

// Supabase publishes the "public" schema through its REST API. Nothing here is meant to be reached
// that way (the API server connects directly), so switch row security on with no policies and take
// the table rights away from the public REST roles. On a plain Postgres those roles do not exist.
export async function lockDown(schema) {
  await sqlExec(`
    DO $lock$
    DECLARE t record;
    BEGIN
      FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = '${schema}' LOOP
        EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', '${schema}', t.tablename);
      END LOOP;
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA ${schema} FROM anon, authenticated';
      END IF;
    END
    $lock$;
  `)
}
