// Hindi text for the Keeper and Admin apps (English phrase -> Hindi).
// Text that is not listed stays in English. Add a line here to translate more.
export const hi = {
  // ---- shared / status ----
  'Honey Chain': 'हनी चेन', 'Honey Chain Admin': 'हनी चेन एडमिन', 'Honey Chain Keeper': 'हनी चेन कीपर',
  'Admin · KVIC Portal': 'एडमिन · केवीआईसी पोर्टल', 'Admin · KVIC Control Portal': 'एडमिन · केवीआईसी कंट्रोल पोर्टल',
  'Pending': 'लंबित', 'Approved': 'स्वीकृत', 'Rejected': 'अस्वीकृत', 'Suspended': 'निलंबित', 'Verified': 'सत्यापित',
  'Harvested': 'शहद निकाला गया', 'Lab tested': 'प्रयोगशाला जाँच पूरी', 'Lab review': 'प्रयोगशाला समीक्षा', 'In transit': 'रास्ते में',
  'Created': 'बनाया गया', 'Closing': 'बंद हो रहा', 'Closed': 'बंद', 'Active': 'सक्रिय', 'Deactivated': 'निष्क्रिय',
  'Cancel': 'रद्द करें', 'Close': 'बंद करें', 'Save': 'सहेजें', 'View': 'देखें', 'Open': 'खुले', 'Decided': 'निर्णय हो चुके',
  'All': 'सभी', 'Search': 'खोजें', 'Loading…': 'लोड हो रहा है…', 'Loading...': 'लोड हो रहा है…', 'Never': 'कभी नहीं',
  'Batch': 'बैच', 'Honey': 'शहद', 'Quantity': 'मात्रा', 'Status': 'स्थिति', 'Date': 'तिथि', 'Amount': 'राशि', 'Action': 'कार्रवाई',
  'Actions': 'कार्रवाइयाँ', 'Type': 'प्रकार', 'Name': 'नाम', 'Total': 'कुल', 'Note': 'टिप्पणी', 'Reason': 'कारण',

  // ---- admin shell ----
  'Control room': 'कंट्रोल रूम', 'Review queue': 'समीक्षा कतार', 'Organizations': 'संगठन', 'Blockchain': 'ब्लॉकचेन',
  'Income & production': 'आय और उत्पादन', 'Officers': 'अधिकारी', 'Activity & approvals': 'गतिविधि और स्वीकृतियाँ',
  'My activity': 'मेरी गतिविधि', 'Overview': 'सारांश', 'Network': 'नेटवर्क', 'Governance': 'शासन',
  'Sign out': 'साइन आउट', 'KVIC head': 'केवीआईसी प्रमुख', 'State officer': 'राज्य अधिकारी', 'Regional officer': 'क्षेत्रीय अधिकारी',
  'National programme': 'राष्ट्रीय कार्यक्रम', 'Organizations ': 'संगठन',

  // ---- admin login ----
  'Officer sign in': 'अधिकारी साइन इन', 'KVIC Head, State Officers and Regional Officers only.': 'केवल केवीआईसी प्रमुख, राज्य और क्षेत्रीय अधिकारियों के लिए।',
  'Username': 'उपयोगकर्ता नाम', 'Password': 'पासवर्ड', 'Sign in': 'साइन इन', 'Signing in…': 'साइन इन हो रहा है…',
  'Login details (demo, click to fill)': 'लॉगिन विवरण (डेमो, भरने के लिए क्लिक करें)',
  'KVIC Head': 'केवीआईसी प्रमुख', 'All states, officers, approvals and audit': 'सभी राज्य, अधिकारी, स्वीकृतियाँ और ऑडिट',
  'State Officer': 'राज्य अधिकारी', 'Tamil Nadu: regions, production, income, blockchain': 'तमिलनाडु: क्षेत्र, उत्पादन, आय, ब्लॉकचेन',
  'Regional Officer': 'क्षेत्रीय अधिकारी', 'One login for every registration location. Choose one to fill it in.': 'हर पंजीकरण स्थान के लिए एक लॉगिन। भरने के लिए एक चुनें।',
  'Choose a location…': 'स्थान चुनें…',

  // ---- admin dashboard ----
  'Everything below updates live as beekeepers and officers make changes.': 'नीचे सब कुछ तुरंत अपडेट होता है जब मधुमक्खी पालक और अधिकारी बदलाव करते हैं।',
  'Honey recorded': 'दर्ज शहद', 'Bottle QR codes': 'बोतल क्यूआर कोड', 'Income this month': 'इस माह की आय', 'Pending reviews': 'लंबित समीक्षाएँ',
  'need a decision': 'निर्णय चाहिए', 'on the chain': 'ब्लॉकचेन पर', 'all companies': 'सभी कंपनियाँ', 'Honey produced': 'शहद उत्पादन',
  'Kilograms harvested per month, from batches on the chain': 'ब्लॉकचेन के बैच से प्रति माह निकाला गया शहद (किलोग्राम)',
  'Needs attention': 'ध्यान चाहिए', 'Open items in your jurisdiction': 'आपके क्षेत्राधिकार के खुले मामले',
  'Decide who joins the KVIC monitoring chain': 'तय करें कौन केवीआईसी निगरानी श्रृंखला में शामिल हो',
  'Shared by beekeepers for verification': 'सत्यापन के लिए मधुमक्खी पालकों द्वारा साझा', 'Review': 'समीक्षा', 'Monthly income': 'मासिक आय',
  'Total reported by companies in your jurisdiction': 'आपके क्षेत्राधिकार की कंपनियों द्वारा बताई गई कुल आय', 'Full report': 'पूरी रिपोर्ट',
  'Latest batches': 'नवीनतम बैच', 'Newest harvests recorded on the shared chain': 'साझा ब्लॉकचेन पर दर्ज सबसे नए बैच',
  'Open blockchain': 'ब्लॉकचेन खोलें', 'No batches recorded yet.': 'अभी कोई बैच दर्ज नहीं है।', 'Loading the latest figures…': 'ताज़ा आँकड़े लोड हो रहे हैं…',
  'Blockchain verified': 'ब्लॉकचेन सत्यापित', 'Blockchain integrity problem': 'ब्लॉकचेन में गड़बड़ी', 'States': 'राज्य', 'Regions': 'क्षेत्र',
  'Production, verification and officer performance by state': 'राज्यवार उत्पादन, सत्यापन और अधिकारियों का प्रदर्शन',
  'Regional production and how quickly regional officers work through their queues': 'क्षेत्रीय उत्पादन और क्षेत्रीय अधिकारी अपनी कतार कितनी जल्दी निपटाते हैं',
  'Organisation': 'संगठन', 'State': 'राज्य', 'Region': 'क्षेत्र', 'Orgs': 'संगठन', 'Bottles': 'बोतलें', 'Labs verified': 'सत्यापित प्रयोगशाला',
  'Avg org approval': 'औसत पंजीकरण मंज़ूरी', 'Avg lab review': 'औसत प्रयोगशाला समीक्षा', 'Income (month)': 'आय (माह)', 'None assigned': 'कोई नियुक्त नहीं',
  'waiting for a decision in your jurisdiction': 'आपके क्षेत्राधिकार में निर्णय की प्रतीक्षा में',

  // ---- admin requests / closures ----
  'Registrations': 'पंजीकरण', 'Lab results': 'प्रयोगशाला परिणाम', 'Closures': 'बंदी', 'Organisation registrations': 'संगठन पंजीकरण', 'Company closures': 'कंपनी बंदी',
  'Decide which organisations join the KVIC monitoring chain and verify the lab results beekeepers share.': 'तय करें कौन से संगठन केवीआईसी निगरानी श्रृंखला में शामिल हों और मधुमक्खी पालकों के साझा प्रयोगशाला परिणाम सत्यापित करें।',
  'Accept into KVIC chain': 'केवीआईसी श्रृंखला में स्वीकार करें', 'Reject': 'अस्वीकार करें', 'Verify and sign': 'सत्यापित करें और हस्ताक्षर करें',
  'Government formalities': 'सरकारी औपचारिकताएँ', 'Complete closure': 'बंदी पूरी करें', 'Decline (needs a note)': 'अस्वीकार करें (टिप्पणी ज़रूरी)',
  'Closing note (recorded in the audit log)': 'समापन टिप्पणी (ऑडिट लॉग में दर्ज)', 'AI-assisted review': 'AI-सहायता प्राप्त समीक्षा',
  'Confirm your password to sign': 'हस्ताक्षर के लिए अपने पासवर्ड की पुष्टि करें', 'Note (optional)': 'टिप्पणी (वैकल्पिक)',
  'Reason (shown to the beekeeper)': 'कारण (मधुमक्खी पालक को दिखेगा)', 'Accept': 'स्वीकार करें', 'Suspend': 'निलंबित करें', 'Reinstate': 'बहाल करें',
  'Start closure': 'बंदी शुरू करें', 'View blockchain': 'ब्लॉकचेन देखें', 'Batches': 'बैच', 'Decision history': 'निर्णय इतिहास', 'Closure record': 'बंदी रिकॉर्ड',
  'Governance ': 'शासन', 'Registration no. (KVIC)': 'पंजीकरण संख्या (केवीआईसी)', 'FSSAI licence': 'एफएसएसएआई लाइसेंस', 'GSTIN': 'जीएसटीआईएन',
  'Not provided': 'उपलब्ध नहीं', 'Contact': 'संपर्क', 'Certificate says': 'प्रमाणपत्र के अनुसार', 'Antibiotic residue': 'एंटीबायोटिक अवशेष',
  'Open lab requests / reviews': 'खुले प्रयोगशाला अनुरोध / समीक्षाएँ', 'Honey still recorded with keeper': 'कीपर के पास अभी दर्ज शहद',
  'Keeper declarations': 'कीपर की घोषणाएँ', 'Officer-initiated': 'अधिकारी द्वारा शुरू',
  'Search by name, code or registration no.': 'नाम, कोड या पंजीकरण संख्या से खोजें', 'Network directory': 'नेटवर्क निर्देशिका',
  'Every registered beekeeper and startup in your jurisdiction, with what they have produced on the chain.': 'आपके क्षेत्राधिकार का हर पंजीकृत मधुमक्खी पालक और स्टार्टअप, और उन्होंने ब्लॉकचेन पर क्या उत्पादन दर्ज किया।',
  'No organisations match this filter.': 'इस फ़िल्टर से कोई संगठन नहीं मिला।', 'Loading organisation…': 'संगठन लोड हो रहा है…',
  'Start closure of': 'बंदी शुरू करें:', 'Reason for closure': 'बंदी का कारण', 'Formal deregistration': 'औपचारिक पंजीकरण समाप्ति',

  // ---- admin chain / officers / activity / reports ----
  'Shared secure ledger': 'साझा सुरक्षित बहीखाता', 'Blocks': 'ब्लॉक', 'Batch chains': 'बैच श्रृंखलाएँ', 'Search records': 'रिकॉर्ड खोजें',
  'Verify every block now': 'हर ब्लॉक अभी सत्यापित करें', 'Verifying…': 'सत्यापित हो रहा है…', 'Transactions': 'लेनदेन', 'Head hash': 'हेड हैश',
  'Validator': 'वैलिडेटर', 'Genesis block': 'जेनेसिस ब्लॉक', 'Load older blocks': 'पुराने ब्लॉक लोड करें', 'Chain of custody': 'हस्तांतरण श्रृंखला',
  'Packaging batches': 'पैकेजिंग बैच', 'Add officer': 'अधिकारी जोड़ें', 'Create officer': 'अधिकारी बनाएँ', 'Officer': 'अधिकारी', 'Role': 'भूमिका',
  'Jurisdiction': 'क्षेत्राधिकार', 'Access': 'पहुँच', 'Last sign-in': 'अंतिम साइन-इन', 'Decisions': 'निर्णय', 'Waiting': 'प्रतीक्षा में',
  'Deactivate': 'निष्क्रिय करें', 'Activate': 'सक्रिय करें', 'Reset': 'रीसेट', 'Activity': 'गतिविधि', 'All activity': 'सारी गतिविधि',
  'Approvals only': 'केवल स्वीकृतियाँ', 'All officers': 'सभी अधिकारी', 'Supervision': 'निगरानी', 'No activity recorded yet.': 'अभी कोई गतिविधि दर्ज नहीं है।',
  'Export CSV': 'CSV निर्यात करें', 'Income reported': 'बताई गई आय', 'Honey harvested': 'निकाला गया शहद', 'Bottles this month': 'इस माह की बोतलें',
  'Bottles all time': 'कुल बोतलें', 'Company': 'कंपनी', 'Honey (kg)': 'शहद (किग्रा)', 'Bottles total': 'कुल बोतलें', 'Income': 'आय',
  'State and national oversight': 'राज्य और राष्ट्रीय निगरानी', 'Signed in': 'साइन इन किया', 'Organisation decision': 'संगठन निर्णय',
  'Lab result decision': 'प्रयोगशाला परिणाम निर्णय', 'Email': 'ईमेल', 'Phone': 'फ़ोन',

  // ---- keeper shell / nav ----
  'OVERVIEW': 'सारांश', 'BEEKEEPING': 'मधुमक्खी पालन', 'BUSINESS': 'व्यवसाय', 'TRACEABILITY': 'ट्रेसेबिलिटी', 'SYSTEM': 'सिस्टम',
  'Dashboard': 'डैशबोर्ड', 'My Hives': 'मेरे छत्ते', 'Harvest': 'शहद निकालना', 'Inventory': 'भंडार', 'Laboratory': 'प्रयोगशाला',
  'Supply Chain': 'आपूर्ति श्रृंखला', 'Buyers': 'खरीदार', 'Orders': 'ऑर्डर', 'Billing': 'बिलिंग', 'Finance': 'वित्त', 'AI Insights': 'AI अंतर्दृष्टि',
  'Traceability': 'ट्रेसेबिलिटी', 'QR Management': 'क्यूआर प्रबंधन', 'Notifications': 'सूचनाएँ', 'Settings': 'सेटिंग्स', 'Sign Out': 'साइन आउट',
  'Keeper': 'कीपर', 'Live operations console': 'लाइव संचालन कंसोल', 'Search workspace': 'कार्यस्थान खोजें', 'Workspace': 'कार्यस्थान',
  'Loading your workspace…': 'आपका कार्यस्थान लोड हो रहा है…',

  // ---- keeper login ----
  'Welcome back.': 'वापसी पर स्वागत है।', 'Sign in to your beekeeper dashboard.': 'अपने मधुमक्खी पालक डैशबोर्ड में साइन इन करें।',
  'Secure workspace': 'सुरक्षित कार्यस्थान', 'Sign In': 'साइन इन', 'Please wait...': 'कृपया प्रतीक्षा करें...', 'Register a new organisation': 'नया संगठन पंजीकृत करें',
  'Already registered? Sign in': 'पहले से पंजीकृत हैं? साइन इन करें', 'Join the KVIC monitoring chain': 'केवीआईसी निगरानी श्रृंखला से जुड़ें',
  'Register your organisation.': 'अपने संगठन को पंजीकृत करें।', 'Submit for approval': 'स्वीकृति के लिए भेजें', 'Full Name': 'पूरा नाम',
  'Organisation / Farm Name': 'संगठन / फ़ार्म का नाम', 'How are you registered?': 'आप कैसे पंजीकृत हैं?', 'KVIC Madhukranti ID': 'केवीआईसी मधुक्रांति आईडी',
  'Registration number': 'पंजीकरण संख्या', 'Issuing organisation': 'जारी करने वाली संस्था', 'FSSAI licence number': 'एफएसएसएआई लाइसेंस संख्या',
  'KVIC region': 'केवीआईसी क्षेत्र', 'Select state': 'राज्य चुनें', 'Select region': 'क्षेत्र चुनें', 'Business Email': 'व्यावसायिक ईमेल',
  'Your regional KVIC officer reviews these details before your honey can be recorded on the chain.': 'आपका शहद ब्लॉकचेन पर दर्ज होने से पहले आपके क्षेत्रीय केवीआईसी अधिकारी इन विवरणों की जाँच करेंगे।',
  'Beekeeper registered with KVIC (Honey Mission)': 'केवीआईसी (हनी मिशन) में पंजीकृत मधुमक्खी पालक',
  'Beekeeper registered through another organisation (SHG / FPO / NGO)': 'अन्य संस्था (एसएचजी / एफपीओ / एनजीओ) के माध्यम से पंजीकृत मधुमक्खी पालक',
  'Local honey startup / food business': 'स्थानीय शहद स्टार्टअप / खाद्य व्यवसाय', 'Intelligent apiary operations': 'बुद्धिमान मधुशाला संचालन',
  'From hive health to honey traceability, keep every decision grounded in the field.': 'छत्ते के स्वास्थ्य से शहद की ट्रेसेबिलिटी तक, हर निर्णय को ज़मीनी हकीकत से जोड़े रखें।',
  'Field visibility': 'क्षेत्र की निगरानी', 'Batch traceability': 'बैच ट्रेसेबिलिटी', 'Honey Chain Keeper • Smart Beekeeping Platform': 'हनी चेन कीपर • स्मार्ट मधुमक्खी पालन प्लेटफ़ॉर्म',
  'Login details': 'लॉगिन विवरण', 'Beekeeper (Ravi Honey Farm)': 'मधुमक्खी पालक (रवि हनी फ़ार्म)',
  'Click to fill. Approved organisation with sample data.': 'भरने के लिए क्लिक करें। स्वीकृत संगठन।',

  // ---- keeper status screen ----
  'Your registration is under review': 'आपका पंजीकरण समीक्षाधीन है', 'Registration not approved': 'पंजीकरण स्वीकृत नहीं हुआ', 'Organisation suspended': 'संगठन निलंबित',
  'Closure in progress': 'बंदी प्रक्रिया जारी', 'Organisation closed': 'संगठन बंद', 'Withdraw request': 'अनुरोध वापस लें',
  'Your regional KVIC officer is verifying your organisation details and credentials. You will get access to Honey Chain Keeper as soon as it is approved. This page updates automatically.': 'आपके क्षेत्रीय केवीआईसी अधिकारी आपके संगठन के विवरण और दस्तावेज़ों की जाँच कर रहे हैं। मंज़ूरी मिलते ही आपको हनी चेन कीपर तक पहुँच मिल जाएगी। यह पृष्ठ अपने आप अपडेट होता है।',
  'Checking for the officer\'s decision…': 'अधिकारी के निर्णय की जाँच हो रही है…',

  // ---- keeper dashboard / hives / harvest ----
  'Total Hives': 'कुल छत्ते', 'Honey Stock': 'शहद भंडार', 'Bottle QR Codes': 'बोतल क्यूआर कोड', 'Income This Month': 'इस माह की आय',
  'Apiary today': 'आज की मधुशाला', 'Every hive tells a story. Keep yours healthy.': 'हर छत्ता एक कहानी कहता है। अपने छत्तों को स्वस्थ रखें।',
  'Income trend': 'आय का रुझान', 'Last 6 months': 'पिछले 6 माह', 'Apiary Overview': 'मधुशाला सारांश', 'Your registered hives': 'आपके पंजीकृत छत्ते',
  'Quick Actions': 'त्वरित कार्य', 'Record Harvest': 'शहद निकालना दर्ज करें', 'Share Lab Result': 'प्रयोगशाला परिणाम साझा करें',
  'Create Bottle QR Codes': 'बोतल क्यूआर कोड बनाएँ', 'Add Transaction': 'लेनदेन जोड़ें', 'Recent Activity': 'हाल की गतिविधि', 'Attention Required': 'ध्यान आवश्यक',
  'IoT devices not connected': 'आईओटी उपकरण जुड़े नहीं हैं', 'Add Hive': 'छत्ता जोड़ें', 'Search hives...': 'छत्ते खोजें...',
  'Create, connect, and monitor every hive from one workspace.': 'एक ही जगह से हर छत्ता बनाएँ, जोड़ें और निगरानी करें।',
  'View Hive Monitoring': 'छत्ते की निगरानी देखें', 'Create hive': 'छत्ता बनाएँ', 'Create Hive': 'छत्ता बनाएँ', 'Hive name': 'छत्ते का नाम', 'Location': 'स्थान',
  'Record honey harvests and create traceable batches.': 'शहद निकालना दर्ज करें और ट्रेस करने योग्य बैच बनाएँ।', 'Total Harvest': 'कुल शहद निकाला', 'This Month': 'इस माह',
  'Batches Created': 'बने बैच', 'Active Hives': 'सक्रिय छत्ते', 'Recent Harvests': 'हाल का शहद निकालना', 'Record New Harvest': 'नया शहद निकालना दर्ज करें',
  'Hive': 'छत्ता', 'Harvest Date': 'निकालने की तिथि', 'Quantity (kg)': 'मात्रा (किग्रा)', 'Honey Type': 'शहद का प्रकार', 'Harvest Location': 'निकालने का स्थान',
  'Notes': 'टिप्पणियाँ', 'Batch ID': 'बैच आईडी', 'Why is the Batch ID important?': 'बैच आईडी क्यों ज़रूरी है?',
  'Search batch ID, hive or honey type...': 'बैच आईडी, छत्ता या शहद का प्रकार खोजें...', 'Harvest Batch': 'शहद बैच', 'On chain': 'ब्लॉकचेन पर',

  // ---- keeper laboratory / QR / supply chain ----
  'Request Lab Test': 'प्रयोगशाला जाँच का अनुरोध', 'Requests': 'अनुरोध', 'Need Certificate': 'प्रमाणपत्र चाहिए', 'With Officer': 'अधिकारी के पास',
  'Laboratory Requests': 'प्रयोगशाला अनुरोध', 'Laboratory': 'प्रयोगशाला', 'Requested': 'अनुरोध की तिथि', 'Certificate': 'प्रमाणपत्र', 'Stage': 'चरण',
  'Submit certificate': 'प्रमाणपत्र जमा करें', 'Awaiting certificate': 'प्रमाणपत्र की प्रतीक्षा', 'With regional officer': 'क्षेत्रीय अधिकारी के पास',
  'Verified & signed': 'सत्यापित और हस्ताक्षरित', 'Request a lab test': 'प्रयोगशाला जाँच का अनुरोध करें', 'Submit the laboratory certificate': 'प्रयोगशाला प्रमाणपत्र जमा करें',
  'Send to regional officer': 'क्षेत्रीय अधिकारी को भेजें', 'Certificate number': 'प्रमाणपत्र संख्या', 'Test date': 'जाँच की तिथि', 'Moisture (%)': 'नमी (%)',
  'HMF (mg/kg)': 'एचएमएफ (मिग्रा/किग्रा)', 'Sucrose (%)': 'सुक्रोज़ (%)', 'Certificate outcome': 'प्रमाणपत्र का परिणाम', 'Passed': 'उत्तीर्ण', 'Failed': 'अनुत्तीर्ण',
  'Not detected': 'नहीं मिला', 'Detected': 'मिला', 'Note for the officer': 'अधिकारी के लिए टिप्पणी', 'CERTIFICATION JOURNEY': 'प्रमाणन की यात्रा',
  'Lab test requested': 'प्रयोगशाला जाँच का अनुरोध', 'Laboratory certificate submitted': 'प्रयोगशाला प्रमाणपत्र जमा', 'Verified and digitally signed': 'सत्यापित और डिजिटल हस्ताक्षरित',
  'Packaging and QR generation unlocked': 'पैकेजिंग और क्यूआर निर्माण खुला', 'Laboratory Requests ': 'प्रयोगशाला अनुरोध',
  'Packaging identity': 'पैकेजिंग पहचान', 'New packaging batch': 'नया पैकेजिंग बैच', 'Source batch': 'स्रोत बैच', 'Product name': 'उत्पाद का नाम', 'Jar size (grams)': 'जार का आकार (ग्राम)',
  'Number of bottles': 'बोतलों की संख्या', 'Create packaging batch': 'पैकेजिंग बैच बनाएँ', 'Bottle QR records': 'बोतल क्यूआर रिकॉर्ड', 'Your packaging batches': 'आपके पैकेजिंग बैच',
  'Go to Laboratory': 'प्रयोगशाला में जाएँ', 'Source Batches': 'स्रोत बैच', 'Bottle QRs Created': 'बने बोतल क्यूआर', 'Verification': 'सत्यापन', 'Public': 'सार्वजनिक', 'View QRs': 'क्यूआर देखें',
  'Follow honey from keeper to distributor, retailer and consumer. Every transfer is sealed on the blockchain.': 'शहद का सफ़र कीपर से वितरक, खुदरा विक्रेता और उपभोक्ता तक देखें। हर हस्तांतरण ब्लॉकचेन पर दर्ज होता है।',
  'Transfer honey': 'शहद हस्तांतरित करें', 'Transfer to': 'हस्तांतरण किसे', 'Record transfer': 'हस्तांतरण दर्ज करें', 'Distributor / wholesaler': 'वितरक / थोक विक्रेता',
  'Retailer': 'खुदरा विक्रेता', 'Consumer': 'उपभोक्ता', 'Invoice number': 'चालान संख्या', 'Locked': 'बंद',

  // ---- keeper business pages ----
  'Distributors, retailers and customers you sell to.': 'वितरक, खुदरा विक्रेता और ग्राहक जिन्हें आप बेचते हैं।', 'Add Buyer': 'खरीदार जोड़ें', 'Total Buyers': 'कुल खरीदार',
  'Paid Purchases': 'भुगतान की गई खरीद', 'Pending Payments': 'लंबित भुगतान', 'Search buyers...': 'खरीदार खोजें...', 'Buyer': 'खरीदार', 'Contact ': 'संपर्क', 'Paid': 'भुगतान हुआ',
  'Save buyer': 'खरीदार सहेजें', 'Add buyer': 'खरीदार जोड़ें', 'Wholesaler': 'थोक विक्रेता', 'Company ': 'कंपनी', 'Direct Consumer': 'सीधे उपभोक्ता',
  'No buyers yet. Add the distributors and retailers you sell to.': 'अभी कोई खरीदार नहीं। जिन वितरकों और खुदरा विक्रेताओं को आप बेचते हैं, उन्हें जोड़ें।',
  'Plan fulfillment from confirmed order to delivery.': 'पक्के ऑर्डर से डिलीवरी तक की योजना बनाएँ।', 'New Order': 'नया ऑर्डर', 'Add a buyer first': 'पहले एक खरीदार जोड़ें',
  'Open orders': 'खुले ऑर्डर', 'Processing': 'प्रक्रिया में', 'Ready to ship': 'भेजने के लिए तैयार', 'Delivered': 'डिलीवर हुआ', 'Fulfillment queue': 'पूर्ति कतार', 'Create Order': 'ऑर्डर बनाएँ',
  'Create invoices and track payment status. A paid invoice is booked as income in Finance.': 'चालान बनाएँ और भुगतान की स्थिति देखें। भुगतान हुआ चालान वित्त में आय के रूप में दर्ज होता है।',
  'Create Invoice': 'चालान बनाएँ', 'Total Invoices': 'कुल चालान', 'Pending ': 'लंबित', 'Invoices': 'चालान', 'Mark paid': 'भुगतान हुआ चिह्नित करें', 'Cancelled': 'रद्द', 'Invoice preview': 'चालान का पूर्वावलोकन',
  'Create invoice': 'चालान बनाएँ', 'Invoice date': 'चालान की तिथि', 'Due date': 'देय तिथि', 'Items': 'वस्तुएँ', 'Subtotal': 'उप-योग', 'GST (%)': 'जीएसटी (%)', 'GST': 'जीएसटी',
  '+ Add another item': '+ एक और वस्तु जोड़ें', 'Download / print': 'डाउनलोड / प्रिंट',
  'Honey stock worked out from your harvests, bottles and supply-chain transfers.': 'आपके शहद निकालने, बोतलों और आपूर्ति श्रृंखला हस्तांतरण से निकाला गया शहद भंडार।',
  'Total Harvested': 'कुल निकाला गया', 'In Your Hands': 'आपके पास', 'Sent Down the Chain': 'आगे भेजा गया', 'Batch Inventory': 'बैच भंडार', 'In hand': 'हाथ में', 'In bottles': 'बोतलों में',
  'QUANTITY LEDGER': 'मात्रा बहीखाता',
  'Understand cash flow, profitability, and operating costs across the apiary.': 'पूरी मधुशाला का नकदी प्रवाह, लाभ और संचालन लागत समझें।', 'This month': 'इस माह', 'Last month': 'पिछला माह',
  'This quarter': 'इस तिमाही', 'Revenue': 'राजस्व', 'Operating costs': 'संचालन लागत', 'Net profit': 'शुद्ध लाभ', 'Cash position': 'नकदी स्थिति', 'Cash flow overview': 'नकदी प्रवाह सारांश',
  'Budget watch': 'बजट निगरानी', 'Six-month financial trend': 'छह माह का वित्तीय रुझान', 'Recent transactions': 'हाल के लेनदेन', 'Export': 'निर्यात', 'Expense': 'खर्च', 'Save transaction': 'लेनदेन सहेजें',
  'AI Finance Intelligence': 'AI वित्त बुद्धिमत्ता', 'Expected Income': 'अपेक्षित आय', 'Expected Expenses': 'अपेक्षित खर्च', 'Expected Profit': 'अपेक्षित लाभ', 'Expected Honey': 'अपेक्षित शहद',
  'Income and expense trend': 'आय और खर्च का रुझान', 'Production economics': 'उत्पादन अर्थशास्त्र', 'Where the money goes': 'पैसा कहाँ जाता है',
  'Decisions your KVIC officers make about your organisation and lab results.': 'आपके संगठन और प्रयोगशाला परिणामों पर केवीआईसी अधिकारियों के निर्णय।', 'Officer decisions': 'अधिकारियों के निर्णय',

  // ---- keeper settings / closure ----
  'Profile': 'प्रोफ़ाइल', 'Farm': 'फ़ार्म', 'Business': 'व्यवसाय', 'IoT Devices': 'आईओटी उपकरण', 'Security': 'सुरक्षा', 'Close organisation': 'संगठन बंद करें',
  'Save Changes': 'बदलाव सहेजें', 'Farm Name': 'फ़ार्म का नाम', 'Number of Hives': 'छत्तों की संख्या', 'Business Name': 'व्यवसाय का नाम', 'Business Address': 'व्यावसायिक पता',
  'Contact Email': 'संपर्क ईमेल', 'Change Password': 'पासवर्ड बदलें', 'Current password': 'वर्तमान पासवर्ड', 'New password': 'नया पासवर्ड',
  'Formally close your organisation with KVIC. This cannot be undone once your officer completes it.': 'अपने संगठन को केवीआईसी के साथ औपचारिक रूप से बंद करें। अधिकारी के पूरा करने के बाद इसे पलटा नहीं जा सकता।',
  'What happens': 'क्या होगा', 'Formalities your officer will check': 'औपचारिकताएँ जो आपके अधिकारी जाँचेंगे', 'Reason for closing': 'बंद करने का कारण', 'Confirm your password': 'अपने पासवर्ड की पुष्टि करें',
  'Request closure': 'बंदी का अनुरोध करें',
  'I have settled all buyer, supplier and staff dues.': 'मैंने सभी खरीदारों, आपूर्तिकर्ताओं और कर्मचारियों की देनदारियाँ चुका दी हैं।',
  'No honey stock is left pending, or it has been sold or disposed of with records.': 'कोई शहद स्टॉक लंबित नहीं है, या वह रिकॉर्ड के साथ बेचा या निपटाया जा चुका है।',
  'I will keep my accounts and tax records for the period the law requires.': 'मैं कानून द्वारा आवश्यक अवधि तक अपने लेखा और कर रिकॉर्ड रखूँगा/रखूँगी।',

  // ---- public verify page inside keeper ----
  'Verified authentic honey': 'सत्यापित असली शहद', 'Not certified': 'प्रमाणित नहीं', 'Product': 'उत्पाद', 'Producer and origin': 'उत्पादक और मूल स्थान',
  'Laboratory verification': 'प्रयोगशाला सत्यापन', 'Traceability history': 'ट्रेसेबिलिटी इतिहास', 'Supply chain journey': 'आपूर्ति श्रृंखला का सफ़र',
  // ---- inspections / audits ----
  'Inspections': 'निरीक्षण', 'Inspection': 'निरीक्षण', 'Schedule inspection': 'निरीक्षण निर्धारित करें', 'Schedule an inspection': 'निरीक्षण निर्धारित करें',
  'Scheduled': 'निर्धारित', 'Reported': 'रिपोर्ट दाख़िल', 'Cancelled': 'रद्द', 'Notice to the keeper': 'पालक को सूचना', 'Send notice': 'सूचना भेजें',
  'Organisation': 'संगठन', 'Choose an organisation…': 'संगठन चुनें…', 'Purpose': 'उद्देश्य', 'Date': 'तारीख़', 'Time (optional)': 'समय (वैकल्पिक)',
  'Routine compliance inspection': 'नियमित अनुपालन निरीक्षण', 'Complaint or consumer report': 'शिकायत या उपभोक्ता रिपोर्ट',
  'Follow-up on a failed or doubtful lab result': 'असफल या संदिग्ध लैब परिणाम पर अनुवर्ती', 'Licence and registration verification': 'लाइसेंस और पंजीकरण सत्यापन',
  'Follow-up on an earlier inspection': 'पिछले निरीक्षण पर अनुवर्ती',
  'Inspection date': 'निरीक्षण की तारीख़', 'Keeper notified': 'पालक को सूचित किया', 'Scheduled by': 'निर्धारित करने वाले', 'Visited on': 'दौरे की तारीख़',
  'Inspector · present at site': 'निरीक्षक · मौक़े पर उपस्थित', 'Outcome': 'परिणाम', 'Stock on site vs chain': 'मौक़े पर स्टॉक बनाम श्रृंखला',
  'File visit report': 'दौरे की रिपोर्ट दाख़िल करें', 'Cancel inspection': 'निरीक्षण रद्द करें', 'Keep it': 'रहने दें', 'File report': 'रिपोर्ट दाख़िल करें',
  'Issue closure notice': 'बंदी नोटिस जारी करें', 'Grounds for closure': 'बंदी के आधार', 'Reason': 'कारण',
  'Checklist': 'जाँच सूची', 'Date of visit': 'दौरे की तारीख़', 'Inspector name': 'निरीक्षक का नाम', 'Who represented the organisation on site?': 'मौक़े पर संगठन का प्रतिनिधित्व किसने किया?',
  'Honey stock counted on site (kg)': 'मौक़े पर गिना गया शहद स्टॉक (किग्रा)', 'Grade': 'ग्रेड', 'Remarks (the keeper will see these)': 'टिप्पणियाँ (पालक इन्हें देखेगा)',
  'Officer-only note (optional)': 'केवल अधिकारी के लिए नोट (वैकल्पिक)', 'What must the keeper fix?': 'पालक को क्या सुधारना होगा?', 'Deadline': 'अंतिम तिथि',
  'Satisfactory': 'संतोषजनक', 'Minor issue': 'छोटी समस्या', 'Major issue': 'बड़ी समस्या', 'Not applicable': 'लागू नहीं',
  'Excellent': 'उत्कृष्ट', 'Good': 'अच्छा', 'Needs improvement': 'सुधार आवश्यक', 'Unsatisfactory': 'असंतोषजनक',
  'No action needed': 'कोई कार्रवाई आवश्यक नहीं', 'Corrective action required': 'सुधारात्मक कार्रवाई आवश्यक', 'Re-inspection required': 'पुनः निरीक्षण आवश्यक', 'Closure recommended': 'बंदी की अनुशंसा',
  'FSSAI licence and registration documents valid and displayed': 'FSSAI लाइसेंस और पंजीकरण दस्तावेज़ वैध और प्रदर्शित', 'Apiary and hive condition': 'मधुशाला और छत्तों की स्थिति',
  'Extraction and processing hygiene': 'निष्कर्षण और प्रसंस्करण स्वच्छता', 'Honey storage and food-grade containers': 'शहद भंडारण और फ़ूड-ग्रेड डिब्बे', 'Harvest, sales and batch records kept': 'फ़सल, बिक्री और बैच रिकॉर्ड रखे गए',
  'Packaging and labelling (batch number, QR, FSSAI number)': 'पैकेजिंग और लेबलिंग (बैच नंबर, QR, FSSAI नंबर)', 'Physical stock matches the blockchain record': 'भौतिक स्टॉक ब्लॉकचेन रिकॉर्ड से मेल खाता है',
  'No sign of adulteration (added sugar or syrup)': 'मिलावट का कोई संकेत नहीं (चीनी या सिरप)',
  'Inspection notice': 'निरीक्षण सूचना', 'Acknowledge notice': 'सूचना स्वीकार करें', 'Acknowledged': 'स्वीकार किया', 'Acknowledge': 'स्वीकार करें', 'View': 'देखें',
  'Please keep ready:': 'कृपया तैयार रखें:', 'Past inspections': 'पिछले निरीक्षण', "Officer's remarks:": 'अधिकारी की टिप्पणियाँ:',
  'Inspection today': 'आज निरीक्षण', 'Reminder: inspection tomorrow': 'याद दिलाना: कल निरीक्षण', 'Inspection scheduled': 'निरीक्षण निर्धारित',
  'KVIC officers give you at least one day of notice before visiting. After the visit you can read the grade and remarks here.': 'KVIC अधिकारी दौरे से कम से कम एक दिन पहले सूचना देते हैं। दौरे के बाद आप यहाँ ग्रेड और टिप्पणियाँ पढ़ सकते हैं।',
  'No inspections yet. Notices and reports will appear here.': 'अभी कोई निरीक्षण नहीं। सूचनाएँ और रिपोर्ट यहाँ दिखेंगी।',
  'Schedule an inspection (the keeper is notified straight away and reminded the day before), record what you found on the visit, and issue a closure notice when an audit warrants it.': 'निरीक्षण निर्धारित करें (पालक को तुरंत सूचना और एक दिन पहले याद दिलाया जाता है), दौरे में जो पाया उसे दर्ज करें, और ऑडिट में ज़रूरी होने पर बंदी नोटिस जारी करें।',
  'Inspection report filed': 'निरीक्षण रिपोर्ट दाख़िल हुई',

  // ---- notice board, help, schemes, bell ----
  'Notice board': 'सूचना पट्ट', 'From your KVIC offices': 'आपके KVIC कार्यालयों से', 'Important notices from your offices': 'आपके कार्यालयों की महत्वपूर्ण सूचनाएँ',
  'Government Schemes': 'सरकारी योजनाएँ', 'Help & Support': 'सहायता और समर्थन', 'Help & roles': 'सहायता और भूमिकाएँ', 'Help and support': 'सहायता और समर्थन',
  'SUPPORT': 'सहायता', 'Notifications': 'सूचनाएँ', 'View all': 'सभी देखें', 'Search workspace': 'कार्यस्थान खोजें', 'Invoices': 'बिल',
  'Loading notices…': 'सूचनाएँ लोड हो रही हैं…', 'Go to a page…': 'किसी पृष्ठ पर जाएँ…',
  'No notices right now. Announcements from your regional, state and national office will be pinned here.': 'अभी कोई सूचना नहीं। आपके क्षेत्रीय, राज्य और राष्ट्रीय कार्यालय की घोषणाएँ यहाँ दिखेंगी।',
  'You are all caught up. Decisions, notices and reminders appear here.': 'सब कुछ देखा जा चुका है। निर्णय, सूचनाएँ और अनुस्मारक यहाँ दिखते हैं।',
  'Urgent': 'अत्यावश्यक', 'Important': 'महत्वपूर्ण', 'Notice': 'सूचना',
  'New notice': 'नई सूचना', 'All notices': 'सभी सूचनाएँ', 'Sent by you': 'आपके द्वारा भेजी', 'Sent to you': 'आपको भेजी गई', 'For keepers in your area': 'आपके क्षेत्र के कीपर्स के लिए', 'Oversight': 'निगरानी',
  'Title': 'शीर्षक', 'Message': 'संदेश', 'Priority': 'प्राथमिकता', 'Who should read it?': 'इसे कौन पढ़े?', 'Send notice': 'सूचना भेजें',
  'Keepers': 'कीपर्स', 'State officers': 'राज्य अधिकारी', 'Regional officers': 'क्षेत्रीय अधिकारी', 'Limit to regions': 'क्षेत्रों तक सीमित करें', 'Limit to states': 'राज्यों तक सीमित करें',
  'Or send only to specific keepers': 'या केवल चुने हुए कीपर्स को भेजें', 'Search keepers by name or region': 'नाम या क्षेत्र से कीपर खोजें',
  'Post a notice': 'सूचना डालें', 'Review queue': 'समीक्षा कतार', 'Roles & responsibilities': 'भूमिकाएँ और ज़िम्मेदारियाँ', 'Who covers what': 'कौन क्या संभालता है', 'Keeper questions': 'कीपर के सवाल', 'Quick guides': 'त्वरित गाइड',
  'Your role': 'आपकी भूमिका', 'What you can do': 'आप क्या कर सकते हैं', 'What you cannot do': 'आप क्या नहीं कर सकते', 'National office': 'राष्ट्रीय कार्यालय', 'State officer': 'राज्य अधिकारी', 'Regions': 'क्षेत्र',
  'Send answer': 'उत्तर भेजें', 'Waiting': 'प्रतीक्षा में', 'Answered': 'उत्तर मिला', 'Write your answer to the keeper…': 'कीपर के लिए अपना उत्तर लिखें…',
  'Government schemes for honey and beekeeping': 'शहद और मधुमक्खी पालन के लिए सरकारी योजनाएँ', 'Quick links': 'त्वरित लिंक', 'Official website': 'आधिकारिक वेबसाइट',
  'Stuck on an application or paperwork?': 'आवेदन या कागज़ी काम में अटके हैं?', 'Ask for help': 'सहायता माँगें',
  'Apiary today': 'आज की मधुशाला', 'Every hive tells a story. Keep yours healthy.': 'हर छत्ता एक कहानी कहता है। अपने छत्तों को स्वस्थ रखें।',
  'Track hive health, honey production, lab results and farm finances from one clear workspace.': 'छत्तों का स्वास्थ्य, शहद उत्पादन, लैब परिणाम और खेत का वित्त एक ही स्पष्ट कार्यस्थान में देखें।',
  'Everything below updates live as beekeepers and officers make changes.': 'मधुमक्खी पालक और अधिकारी जो बदलाव करते हैं, नीचे सब कुछ लाइव अपडेट होता है।',
  'No notices yet. Use “New notice” to post the first one.': 'अभी कोई सूचना नहीं। पहली सूचना डालने के लिए “नई सूचना” दबाएँ।',
  'Loading the directory…': 'निर्देशिका लोड हो रही है…',

  // ---- loose honey sales ----
  'New sale': 'नई बिक्री', 'Sales': 'बिक्री', 'Honey available': 'उपलब्ध शहद', 'Honey harvested': 'निकाला गया शहद', 'Sold loose': 'खुला बेचा', 'Sales value': 'बिक्री का मूल्य', 'Payment pending': 'भुगतान बाकी',
  'across your batches': 'आपके सभी बैच में', 'to collect from wholesalers': 'थोक व्यापारियों से वसूलना है', 'Paid': 'भुगतान हुआ', 'Cancelled': 'रद्द',
  'After harvest, sell your honey loose to a wholesaler in kg or grams at an agreed price per kg. The wholesaler tests it themselves and sells it on. Every sale is billed, booked as income and sealed on the blockchain.': 'फ़सल के बाद अपना शहद थोक व्यापारी को किलो या ग्राम में, तय प्रति किलो भाव पर खुला बेचें। थोक व्यापारी उसकी जाँच ख़ुद करता है और आगे बेचता है। हर बिक्री का बिल बनता है, आय में दर्ज होती है और ब्लॉकचेन पर सील होती है।',
  'Selling loose honey does not need a KVIC lab certificate. Honey you pack into your own QR jars still must be lab-verified first, and it counts against what is left in the batch.': 'खुला शहद बेचने के लिए KVIC लैब प्रमाणपत्र ज़रूरी नहीं है। अपने QR जार में पैक होने वाला शहद पहले लैब से सत्यापित होना चाहिए, और वह बैच में बचे शहद में गिना जाता है।',
  'Wholesaler / buyer': 'थोक व्यापारी / ख़रीदार', '+ New wholesaler': '+ नया थोक व्यापारी', 'Save wholesaler': 'थोक व्यापारी सहेजें', 'Honey from harvest': 'फ़सल से शहद', 'Quantity sold': 'बेची गई मात्रा',
  'Agreed price per kg (₹)': 'तय भाव प्रति किलो (₹)', 'Sale date': 'बिक्री की तारीख़', 'Pay later': 'बाद में भुगतान', 'Paid now': 'अभी भुगतान', 'Record sale': 'बिक्री दर्ज करें', 'Mark as paid': 'भुगतान हुआ चिह्नित करें',
  'Cancel sale': 'बिक्री रद्द करें', 'View bill': 'बिल देखें', 'Sell this honey': 'यह शहद बेचें', 'Reserved for QR jars': 'QR जार के लिए आरक्षित', 'Available': 'उपलब्ध', 'Nothing left to sell': 'बेचने को कुछ नहीं बचा', 'No sales yet': 'अभी कोई बिक्री नहीं',
  // ---- shipments ----
  'Supply Chain': 'आपूर्ति श्रृंखला', 'New shipment': 'नई खेप', 'Shipments': 'खेपें', 'Ready to ship': 'भेजने के लिए तैयार', 'Batch journey': 'बैच का सफ़र',
  'Jars in stock': 'स्टॉक में जार', 'packed, not yet shipped': 'पैक हैं, अभी भेजे नहीं', 'On the way': 'रास्ते में', 'jars in transit': 'रास्ते में जार', 'Delivered': 'पहुँचा दिया',
  'jars confirmed by you': 'जिन्हें आपने पुष्ट किया', 'sent so far': 'अब तक भेजी गईं', 'Returned to stock': 'स्टॉक में लौटाया',
  'Send your packed jars to buyers, from one batch or several, and follow every shipment until it is delivered. Each hand-over is sealed on the blockchain, so a consumer scanning a jar sees who sold it on.': 'अपने पैक जार ख़रीदारों को भेजें, एक बैच से या कई से, और हर खेप को पहुँचने तक ट्रैक करें। हर हस्तांतरण ब्लॉकचेन पर दर्ज होता है, इसलिए जार स्कैन करने वाला देख सकता है कि उसे किसने आगे बेचा।',
  'No shipments yet': 'अभी कोई खेप नहीं', '1 · Pack jars (QR)': '1 · जार पैक करें (QR)', '2 · Add a buyer': '2 · ख़रीदार जोड़ें', '3 · New shipment': '3 · नई खेप',
  'Mark delivered': 'पहुँचा हुआ चिह्नित करें', 'Return to stock': 'स्टॉक में लौटाएँ', 'Dispatch note': 'डिस्पैच नोट', 'Dispatch': 'भेजना', 'Dispatch shipment': 'खेप भेजें',
  'What is going in this shipment': 'इस खेप में क्या जा रहा है', 'Add jars from another batch': 'दूसरे बैच से जार जोड़ें', 'Dispatch date': 'भेजने की तारीख़', 'Expected delivery': 'अपेक्षित डिलीवरी',
  'Vehicle or courier': 'वाहन या कूरियर', 'Tracking / LR number': 'ट्रैकिंग / एलआर नंबर', 'Invoice number': 'बिल नंबर', 'Buyer': 'ख़रीदार', 'Choose a buyer…': 'ख़रीदार चुनें…',
  'Mark as delivered': 'पहुँचा हुआ चिह्नित करें', 'Confirm delivery': 'डिलीवरी की पुष्टि करें', 'Delivery date': 'डिलीवरी की तारीख़', 'Why is it coming back?': 'यह वापस क्यों आ रहा है?',
  'Jars packed': 'पैक किए जार', 'Shipped': 'भेजे गए', 'In stock': 'स्टॉक में', 'Ship these': 'ये भेजें', 'Awaiting lab verification': 'लैब सत्यापन की प्रतीक्षा', 'All shipped': 'सब भेज दिए', 'No jars packed yet': 'अभी जार पैक नहीं हुए',
  'Laboratory verified': 'लैब से सत्यापित', 'Harvested': 'फ़सल निकाली', 'Consumer': 'उपभोक्ता',
}

// Text that contains numbers or names: [pattern, builder]
export const hiPatterns = [
  [/^Welcome, (.+)\.$/, (name) => `स्वागत है, ${name}।`],
  [/^Good morning, (.+) 👋$/, (name) => `सुप्रभात, ${name} 👋`],
  [/^Live · updated (\d+)s ago$/, (seconds) => `लाइव · ${seconds} सेकंड पहले अपडेट`],
  [/^Connecting…$/, () => 'कनेक्ट हो रहा है…'],
  [/^(\d+) registrations?$/, (count) => `${count} पंजीकरण`],
  [/^(\d+) registration\(s\), (\d+) lab result\(s\)$/, (a, b) => `${a} पंजीकरण, ${b} प्रयोगशाला परिणाम`],
  [/^(\d+) organisation registration\(s\)$/, (count) => `${count} संगठन पंजीकरण`],
  [/^(\d+) lab result\(s\)$/, (count) => `${count} प्रयोगशाला परिणाम`],
  [/^Block #(\d+) · ([\d,]+) transactions signed by (.+)$/, (height, count, validator) => `ब्लॉक #${height} · ${count} लेनदेन, ${validator} द्वारा हस्ताक्षरित`],
  [/^(\d+) awaiting a decision$/, (count) => `${count} निर्णय की प्रतीक्षा में`],
  [/^(\d+) decided$/, (count) => `${count} निर्णय हो चुके`],
  [/^(\d+) registered$/, (count) => `${count} पंजीकृत`],
  [/^(\d+) batches$/, (count) => `${count} बैच`],
  [/^(\d+) hives?$/, (count) => `${count} छत्ते`],
  [/^Block #(\d+) is the chain head$/, (height) => `ब्लॉक #${height} श्रृंखला का शीर्ष है`],
  [/^Packaging is locked for (.+)$/, (batch) => `${batch} के लिए पैकेजिंग बंद है`],
  [/^You hold (.+) kg of this batch\.$/, (kg) => `इस बैच का ${kg} किग्रा आपके पास है।`],
  [/^Forecast for (.+)$/, (month) => `${month} का पूर्वानुमान`],
  [/^Here's what's happening with (.+) today\.$/, (name) => `आज ${name} में क्या चल रहा है।`],
  [/^Report opens (.+)$/, (date) => `रिपोर्ट ${date} से खुलेगी`],
  [/^Visit report for (.+)$/, (name) => `${name} की दौरा रिपोर्ट`],
  [/^Closure notice for (.+)$/, (name) => `${name} के लिए बंदी नोटिस`],
  [/^Cancel (INSP-\d{4}-\d{4})\?$/, (code) => `${code} रद्द करें?`],
  [/^Start closure of (.+)\?$/, (name) => `${name} की बंदी शुरू करें?`],
  [/^(Verify and sign|Accept|Reject|Suspend|Verify) (.+)\?$/, (verb, subject) => `${{ 'Verify and sign': 'सत्यापित करें और हस्ताक्षर करें', Accept: 'स्वीकार करें', Reject: 'अस्वीकार करें', Suspend: 'निलंबित करें', Verify: 'सत्यापित करें' }[verb]}: ${subject}?`],
]
