// Generated by tools/lang/build-web.mjs. Text not listed here stays in English. Have a native speaker review before public release.
export default {
 "nav": {
  "verify": "মধু যাচাই করুন",
  "how": "এটি কীভাবে কাজ করে",
  "schemes": "সরকারি প্রকল্প",
  "honey": "মধু সম্পর্কে",
  "keeper": "কিপার লগইন",
  "admin": "অ্যাডমিন লগইন"
 },
 "hero": {
  "cta": "জার যাচাই করুন",
  "scroll": "মধুর যাত্রা দেখতে স্ক্রল করুন",
  "chapters": [
   {
    "kicker": "হানি চেইন",
    "title": "মৌচাক থেকে ঘর পর্যন্ত।"
   },
   {
    "kicker": "স্মার্ট মৌচাক",
    "title": "যেখান থেকে খুশি দেখা যায় এমন মৌচাক।"
   },
   {
    "kicker": "KVIC দ্বারা যাচাইকৃত",
    "title": "পরীক্ষিত। পর্যালোচিত। স্বাক্ষরিত।"
   },
   {
    "kicker": "একটি স্ক্যান",
    "title": "স্ক্যান করুন। বিশ্বাস করুন। উপভোগ করুন।"
   }
  ]
 },
 "verify": {
  "kicker": "ভোক্তা যাচাই",
  "title": "আপনার মধু কয়েক সেকেন্ডে যাচাই করুন।",
  "button": "যাচাই করুন",
  "scan": "QR স্ক্যান করুন",
  "stopScan": "ক্যামেরা বন্ধ করুন",
  "checking": "হানি চেইন ব্লকচেইন পরীক্ষা করা হচ্ছে…",
  "notFound": "এই কোড হানি চেইনে নিবন্ধিত নয়। জারটি নকল হতে পারে।",
  "another": "আরেকটি যাচাই করুন",
  "sections": {
   "product": "পণ্য",
   "producer": "উৎপাদক ও উৎস",
   "lab": "পরীক্ষাগার যাচাই",
   "approval": "KVIC কর্মকর্তার অনুমোদন ও ডিজিটাল সনদ",
   "history": "ট্রেসেবিলিটির ইতিহাস",
   "chain": "সরবরাহ শৃঙ্খলের যাত্রা"
  },
  "labels": {
   "batch": "ব্যাচ",
   "harvested": "সংগ্রহ",
   "jar": "জার আইডি",
   "bottles": "এই ব্যাচ থেকে জার",
   "producer": "উৎপাদক",
   "origin": "উৎস",
   "fssai": "FSSAI লাইসেন্স",
   "laboratory": "পরীক্ষাগার",
   "certificate": "সনদ",
   "tested": "পরীক্ষিত",
   "approvedBy": "অনুমোদনকারী"
  },
  "signatureValid": "যাচাইকৃত · ডিজিটাল স্বাক্ষর বৈধ",
  "chainOk": "ব্লকচেইন পরীক্ষা: নিরাপদ",
  "chainBad": "ব্লকচেইন পরীক্ষা: ত্রুটি পাওয়া গেছে",
  "verdicts": {
   "VALID": {
    "title": "যাচাইকৃত খাঁটি মধু"
   },
   "NOT_CERTIFIED": {
    "title": "প্রত্যয়িত নয়"
   },
   "UNDER_REVIEW": {
    "title": "পর্যালোচনায় আছে: এই জারে ভরসা করবেন না"
   }
  }
 },
 "schemes": {
  "kicker": "মধু ও মৌমাছি পালনের সরকারি প্রকল্প",
  "title": "মৌমাছি পালকদের জন্য সহায়তা।",
  "visit": "সরকারি ওয়েবসাইট"
 },
 "honey": {
  "kicker": "মধু সম্পর্কে",
  "title": "মধু সম্পর্কে জানার কথা।"
 }
}
