// Generated by tools/lang/build-web.mjs. Text not listed here stays in English. Have a native speaker review before public release.
export default {
 "nav": {
  "verify": "મધ ચકાસો",
  "how": "આ કેવી રીતે કામ કરે છે",
  "schemes": "સરકારી યોજનાઓ",
  "honey": "મધ વિશે",
  "keeper": "કીપર લૉગિન",
  "admin": "એડમિન લૉગિન"
 },
 "hero": {
  "cta": "બરણી ચકાસો",
  "scroll": "મધની સફર જોવા સ્ક્રોલ કરો",
  "chapters": [
   {
    "kicker": "હની ચેઇન",
    "title": "મધપૂડાથી ઘર સુધી."
   },
   {
    "kicker": "સ્માર્ટ મધપૂડા",
    "title": "ગમે ત્યાંથી જોઈ શકાય તેવા મધપૂડા."
   },
   {
    "kicker": "KVIC દ્વારા ચકાસાયેલ",
    "title": "ચકાસ્યું. સમીક્ષા કરી. સહી કરી."
   },
   {
    "kicker": "એક સ્કેન",
    "title": "સ્કેન કરો. વિશ્વાસ કરો. માણો."
   }
  ]
 },
 "verify": {
  "kicker": "ગ્રાહક ચકાસણી",
  "title": "તમારું મધ થોડી સેકન્ડમાં ચકાસો.",
  "button": "ચકાસો",
  "scan": "QR સ્કેન કરો",
  "stopScan": "કેમેરા બંધ કરો",
  "checking": "હની ચેઇન બ્લોકચેઇન તપાસી રહ્યું છે…",
  "notFound": "આ કોડ હની ચેઇનમાં નોંધાયેલ નથી. બરણી નકલી હોઈ શકે.",
  "another": "બીજું ચકાસો",
  "sections": {
   "product": "ઉત્પાદન",
   "producer": "ઉત્પાદક અને મૂળ",
   "lab": "પ્રયોગશાળા ચકાસણી",
   "approval": "KVIC અધિકારીની મંજૂરી અને ડિજિટલ પ્રમાણપત્ર",
   "history": "ટ્રેસેબિલિટી ઇતિહાસ",
   "chain": "પુરવઠા શૃંખલાની સફર"
  },
  "labels": {
   "batch": "બેચ",
   "harvested": "લણણી",
   "jar": "બરણી ID",
   "bottles": "આ બેચમાંથી બરણીઓ",
   "producer": "ઉત્પાદક",
   "origin": "મૂળ",
   "fssai": "FSSAI લાઇસન્સ",
   "laboratory": "પ્રયોગશાળા",
   "certificate": "પ્રમાણપત્ર",
   "tested": "ટેસ્ટ",
   "approvedBy": "મંજૂર કરનાર"
  },
  "signatureValid": "ચકાસાયેલ · ડિજિટલ સહી માન્ય",
  "chainOk": "બ્લોકચેઇન તપાસ: સુરક્ષિત",
  "chainBad": "બ્લોકચેઇન તપાસ: ખામી મળી",
  "verdicts": {
   "VALID": {
    "title": "ચકાસાયેલ અસલી મધ"
   },
   "NOT_CERTIFIED": {
    "title": "પ્રમાણિત નથી"
   },
   "UNDER_REVIEW": {
    "title": "સમીક્ષા હેઠળ: આ બરણી પર વિશ્વાસ ન કરો"
   }
  }
 },
 "schemes": {
  "kicker": "મધ અને મધમાખી ઉછેર માટે સરકારી યોજનાઓ",
  "title": "મધમાખી પાલકો માટે ઉપલબ્ધ સહાય.",
  "visit": "સત્તાવાર વેબસાઇટ"
 },
 "honey": {
  "kicker": "મધ વિશે",
  "title": "મધ વિશે જાણવા જેવું."
 }
}
