// Generated by tools/lang/build-web.mjs. Text not listed here stays in English. Have a native speaker review before public release.
export default {
 "nav": {
  "verify": "मध तपासा",
  "how": "हे कसे कार्य करते",
  "schemes": "सरकारी योजना",
  "honey": "मधाबद्दल",
  "keeper": "कीपर लॉगिन",
  "admin": "ॲडमिन लॉगिन"
 },
 "hero": {
  "cta": "बरणी तपासा",
  "scroll": "मधाचा प्रवास पाहण्यासाठी स्क्रोल करा",
  "chapters": [
   {
    "kicker": "हनी चेन",
    "title": "पोळ्यापासून घरापर्यंत."
   },
   {
    "kicker": "स्मार्ट पोळे",
    "title": "कुठूनही पाहता येणारे पोळे."
   },
   {
    "kicker": "KVIC द्वारे सत्यापित",
    "title": "तपासले. पुनरावलोकन केले. स्वाक्षरी केली."
   },
   {
    "kicker": "एकच स्कॅन",
    "title": "स्कॅन करा. विश्वास ठेवा. आनंद घ्या."
   }
  ]
 },
 "verify": {
  "kicker": "ग्राहक सत्यापन",
  "title": "तुमचे मध काही सेकंदांत तपासा.",
  "button": "तपासा",
  "scan": "QR स्कॅन करा",
  "stopScan": "कॅमेरा थांबवा",
  "checking": "हनी चेन ब्लॉकचेन तपासत आहे…",
  "notFound": "हा कोड हनी चेनमध्ये नोंदणीकृत नाही. बरणी बनावट असू शकते.",
  "another": "दुसरे तपासा",
  "sections": {
   "product": "उत्पादन",
   "producer": "उत्पादक आणि मूळ",
   "lab": "प्रयोगशाळा सत्यापन",
   "approval": "KVIC अधिकाऱ्याची मंजुरी आणि डिजिटल प्रमाणपत्र",
   "history": "ट्रेसेबिलिटी इतिहास",
   "chain": "पुरवठा साखळीचा प्रवास"
  },
  "labels": {
   "batch": "बॅच",
   "harvested": "काढणी",
   "jar": "बरणी ID",
   "bottles": "या बॅचमधील बरण्या",
   "producer": "उत्पादक",
   "origin": "मूळ",
   "fssai": "FSSAI परवाना",
   "laboratory": "प्रयोगशाळा",
   "certificate": "प्रमाणपत्र",
   "tested": "चाचणी",
   "approvedBy": "मंजुरी देणारे"
  },
  "signatureValid": "सत्यापित · डिजिटल स्वाक्षरी वैध",
  "chainOk": "ब्लॉकचेन तपासणी: सुरक्षित",
  "chainBad": "ब्लॉकचेन तपासणी: त्रुटी आढळली",
  "verdicts": {
   "VALID": {
    "title": "सत्यापित अस्सल मध"
   },
   "NOT_CERTIFIED": {
    "title": "प्रमाणित नाही"
   },
   "UNDER_REVIEW": {
    "title": "पुनरावलोकनात: या बरणीवर विश्वास ठेवू नका"
   }
  }
 },
 "schemes": {
  "kicker": "मध आणि मधमाशी पालनासाठी सरकारी योजना",
  "title": "मधमाशी पालकांसाठी उपलब्ध सहाय्य.",
  "visit": "अधिकृत संकेतस्थळ"
 },
 "honey": {
  "kicker": "मधाबद्दल",
  "title": "मधाबद्दल जाणून घ्यावे असे."
 }
}
