// Generated by tools/lang/build-web.mjs. Text not listed here stays in English. Have a native speaker review before public release.
export default {
 "nav": {
  "verify": "ਸ਼ਹਿਦ ਦੀ ਜਾਂਚ",
  "how": "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
  "schemes": "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
  "honey": "ਸ਼ਹਿਦ ਬਾਰੇ",
  "keeper": "ਕੀਪਰ ਲਾਗਇਨ",
  "admin": "ਐਡਮਿਨ ਲਾਗਇਨ"
 },
 "hero": {
  "cta": "ਜਾਰ ਦੀ ਜਾਂਚ ਕਰੋ",
  "scroll": "ਸ਼ਹਿਦ ਦਾ ਸਫ਼ਰ ਵੇਖਣ ਲਈ ਸਕ੍ਰੌਲ ਕਰੋ",
  "chapters": [
   {
    "kicker": "ਹਨੀ ਚੇਨ",
    "title": "ਛੱਤੇ ਤੋਂ ਘਰ ਤੱਕ।"
   },
   {
    "kicker": "ਸਮਾਰਟ ਛੱਤੇ",
    "title": "ਕਿਤੋਂ ਵੀ ਵੇਖੇ ਜਾ ਸਕਣ ਵਾਲੇ ਛੱਤੇ।"
   },
   {
    "kicker": "KVIC ਵੱਲੋਂ ਪ੍ਰਮਾਣਿਤ",
    "title": "ਟੈਸਟ ਕੀਤਾ। ਸਮੀਖਿਆ ਕੀਤੀ। ਦਸਤਖਤ ਕੀਤੇ।"
   },
   {
    "kicker": "ਇੱਕ ਸਕੈਨ",
    "title": "ਸਕੈਨ ਕਰੋ। ਭਰੋਸਾ ਕਰੋ। ਆਨੰਦ ਲਓ।"
   }
  ]
 },
 "verify": {
  "kicker": "ਖਪਤਕਾਰ ਪ੍ਰਮਾਣਿਕਤਾ",
  "title": "ਆਪਣੇ ਸ਼ਹਿਦ ਦੀ ਕੁਝ ਸਕਿੰਟਾਂ ਵਿੱਚ ਜਾਂਚ ਕਰੋ।",
  "button": "ਜਾਂਚੋ",
  "scan": "QR ਸਕੈਨ ਕਰੋ",
  "stopScan": "ਕੈਮਰਾ ਬੰਦ ਕਰੋ",
  "checking": "ਹਨੀ ਚੇਨ ਬਲਾਕਚੇਨ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ…",
  "notFound": "ਇਹ ਕੋਡ ਹਨੀ ਚੇਨ ਵਿੱਚ ਰਜਿਸਟਰ ਨਹੀਂ ਹੈ। ਜਾਰ ਨਕਲੀ ਹੋ ਸਕਦਾ ਹੈ।",
  "another": "ਹੋਰ ਜਾਂਚੋ",
  "sections": {
   "product": "ਉਤਪਾਦ",
   "producer": "ਉਤਪਾਦਕ ਅਤੇ ਮੂਲ",
   "lab": "ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਪ੍ਰਮਾਣਿਕਤਾ",
   "approval": "KVIC ਅਧਿਕਾਰੀ ਦੀ ਮਨਜ਼ੂਰੀ ਅਤੇ ਡਿਜੀਟਲ ਸਰਟੀਫਿਕੇਟ",
   "history": "ਟਰੇਸੇਬਿਲਿਟੀ ਇਤਿਹਾਸ",
   "chain": "ਸਪਲਾਈ ਚੇਨ ਦਾ ਸਫ਼ਰ"
  },
  "labels": {
   "batch": "ਬੈਚ",
   "harvested": "ਕਟਾਈ",
   "jar": "ਜਾਰ ID",
   "bottles": "ਇਸ ਬੈਚ ਤੋਂ ਜਾਰ",
   "producer": "ਉਤਪਾਦਕ",
   "origin": "ਮੂਲ",
   "fssai": "FSSAI ਲਾਇਸੰਸ",
   "laboratory": "ਪ੍ਰਯੋਗਸ਼ਾਲਾ",
   "certificate": "ਸਰਟੀਫਿਕੇਟ",
   "tested": "ਟੈਸਟ",
   "approvedBy": "ਮਨਜ਼ੂਰ ਕਰਤਾ"
  },
  "signatureValid": "ਪ੍ਰਮਾਣਿਤ · ਡਿਜੀਟਲ ਦਸਤਖਤ ਵੈਧ",
  "chainOk": "ਬਲਾਕਚੇਨ ਜਾਂਚ: ਸੁਰੱਖਿਅਤ",
  "chainBad": "ਬਲਾਕਚੇਨ ਜਾਂਚ: ਗੜਬੜ ਮਿਲੀ",
  "verdicts": {
   "VALID": {
    "title": "ਪ੍ਰਮਾਣਿਤ ਅਸਲੀ ਸ਼ਹਿਦ"
   },
   "NOT_CERTIFIED": {
    "title": "ਪ੍ਰਮਾਣਿਤ ਨਹੀਂ"
   },
   "UNDER_REVIEW": {
    "title": "ਸਮੀਖਿਆ ਅਧੀਨ: ਇਸ ਜਾਰ 'ਤੇ ਭਰੋਸਾ ਨਾ ਕਰੋ"
   }
  }
 },
 "schemes": {
  "kicker": "ਸ਼ਹਿਦ ਅਤੇ ਮਧੂ ਮੱਖੀ ਪਾਲਣ ਲਈ ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
  "title": "ਮਧੂ ਮੱਖੀ ਪਾਲਕਾਂ ਲਈ ਉਪਲਬਧ ਸਹਾਇਤਾ।",
  "visit": "ਅਧਿਕਾਰਤ ਵੈੱਬਸਾਈਟ"
 },
 "honey": {
  "kicker": "ਸ਼ਹਿਦ ਬਾਰੇ",
  "title": "ਸ਼ਹਿਦ ਬਾਰੇ ਜਾਣਨ ਯੋਗ।"
 }
}
