// Generated by tools/lang/build-web.mjs. Text not listed here stays in English. Have a native speaker review before public release.
export default {
 "nav": {
  "verify": "شہد کی تصدیق",
  "how": "یہ کیسے کام کرتا ہے",
  "schemes": "سرکاری اسکیمیں",
  "honey": "شہد کے بارے میں",
  "keeper": "کیپر لاگ ان",
  "admin": "ایڈمن لاگ ان"
 },
 "hero": {
  "cta": "جار کی تصدیق کریں",
  "scroll": "شہد کا سفر دیکھنے کے لیے اسکرول کریں",
  "chapters": [
   {
    "kicker": "ہنی چین",
    "title": "چھتے سے گھر تک۔"
   },
   {
    "kicker": "اسمارٹ چھتے",
    "title": "کہیں سے بھی دیکھے جا سکنے والے چھتے۔"
   },
   {
    "kicker": "KVIC کی طرف سے تصدیق شدہ",
    "title": "ٹیسٹ شدہ۔ جائزہ شدہ۔ دستخط شدہ۔"
   },
   {
    "kicker": "ایک اسکین",
    "title": "اسکین کریں۔ بھروسہ کریں۔ لطف اٹھائیں۔"
   }
  ]
 },
 "verify": {
  "kicker": "صارف کی تصدیق",
  "title": "اپنے شہد کی چند سیکنڈ میں تصدیق کریں۔",
  "button": "تصدیق کریں",
  "scan": "QR اسکین کریں",
  "stopScan": "کیمرہ بند کریں",
  "checking": "ہنی چین بلاک چین کی جانچ ہو رہی ہے…",
  "notFound": "یہ کوڈ ہنی چین میں رجسٹرڈ نہیں ہے۔ جار جعلی ہو سکتا ہے۔",
  "another": "دوسرا چیک کریں",
  "sections": {
   "product": "مصنوعات",
   "producer": "پیدا کنندہ اور اصل",
   "lab": "تجربہ گاہ کی تصدیق",
   "approval": "KVIC افسر کی منظوری اور ڈیجیٹل سرٹیفکیٹ",
   "history": "ٹریس ایبلٹی کی تاریخ",
   "chain": "سپلائی چین کا سفر"
  },
  "labels": {
   "batch": "بیچ",
   "harvested": "کٹائی",
   "jar": "جار ID",
   "bottles": "اس بیچ سے جار",
   "producer": "پیدا کنندہ",
   "origin": "اصل",
   "fssai": "FSSAI لائسنس",
   "laboratory": "تجربہ گاہ",
   "certificate": "سرٹیفکیٹ",
   "tested": "ٹیسٹ",
   "approvedBy": "منظور کنندہ"
  },
  "signatureValid": "تصدیق شدہ · ڈیجیٹل دستخط درست",
  "chainOk": "بلاک چین جانچ: محفوظ",
  "chainBad": "بلاک چین جانچ: خرابی پائی گئی",
  "verdicts": {
   "VALID": {
    "title": "تصدیق شدہ اصلی شہد"
   },
   "NOT_CERTIFIED": {
    "title": "مصدقہ نہیں"
   },
   "UNDER_REVIEW": {
    "title": "زیر جائزہ: اس جار پر بھروسہ نہ کریں"
   }
  }
 },
 "schemes": {
  "kicker": "شہد اور شہد کی مکھی پالن کے لیے سرکاری اسکیمیں",
  "title": "شہد کی مکھی پالنے والوں کے لیے دستیاب معاونت۔",
  "visit": "سرکاری ویب سائٹ"
 },
 "honey": {
  "kicker": "شہد کے بارے میں",
  "title": "شہد کے بارے میں جاننے کی باتیں۔"
 }
}
