// Builds the website's per-language overrides from web-rows.txt.
// Each row is: dotted.path ¦ ta ¦ te ¦ kn ¦ ml ¦ mr ¦ bn ¦ gu ¦ pa ¦ or ¦ ur
// Numeric path parts are array positions (hero.chapters.0.title). Everything else stays English.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..', '..')
const CODES = ['ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'ur']
const trees = Object.fromEntries(CODES.map((code) => [code, {}]))
let problems = 0
let rows = 0

fs.readFileSync(path.join(here, 'web-rows.txt'), 'utf8').split(/\r?\n/).forEach((line, index) => {
  if (!line.trim()) return
  const cells = line.split('¦').map((cell) => cell.trim())
  if (cells.length !== CODES.length + 1 || cells.some((cell) => !cell)) {
    console.error(`web-rows.txt:${index + 1} has ${cells.length} columns (expected ${CODES.length + 1})`)
    problems += 1
    return
  }
  rows += 1
  const parts = cells[0].split('.')
  CODES.forEach((code, column) => {
    let node = trees[code]
    parts.forEach((part, position) => {
      const last = position === parts.length - 1
      const key = /^\d+$/.test(part) ? Number(part) : part
      if (last) { node[key] = cells[column + 1]; return }
      const nextIsIndex = /^\d+$/.test(parts[position + 1])
      node[key] = node[key] || (nextIsIndex ? [] : {})
      node = node[key]
    })
  })
})

if (problems) process.exit(1)

const dir = path.join(root, 'honeychain-web', 'src', 'lang')
fs.mkdirSync(dir, { recursive: true })
for (const code of CODES) {
  fs.writeFileSync(path.join(dir, `${code}.js`), `// Generated by tools/lang/build-web.mjs. Text not listed here stays in English. Have a native speaker review before public release.\nexport default ${JSON.stringify(trees[code], null, 1)}\n`)
}
fs.copyFileSync(path.join(root, 'APICtech/frontend/src/languages.js'), path.join(root, 'honeychain-web', 'src', 'languages.js'))
console.log(`${rows} website strings x ${CODES.length} languages written`)
