// Builds the per-language dictionaries from the translation tables in rows*.txt.
// Each row is: English ¦ ta ¦ te ¦ kn ¦ ml ¦ mr ¦ bn ¦ gu ¦ pa ¦ or ¦ ur
// Run: node tools/lang/build.mjs   (writes src/lang/<code>.js in the keeper and admin apps)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..', '..')
const CODES = ['ta', 'te', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'ur']
const tables = Object.fromEntries(CODES.map((code) => [code, {}]))
let rows = 0
let problems = 0

for (const file of fs.readdirSync(here).filter((name) => /^rows.*\.txt$/.test(name)).sort()) {
  fs.readFileSync(path.join(here, file), 'utf8').split(/\r?\n/).forEach((line, index) => {
    if (!line.trim()) return
    const cells = line.split('¦').map((cell) => cell.trim())
    if (cells.length !== CODES.length + 1 || cells.some((cell) => !cell)) {
      console.error(`${file}:${index + 1} has ${cells.length} columns (expected ${CODES.length + 1}): ${line.slice(0, 60)}`)
      problems += 1
      return
    }
    rows += 1
    CODES.forEach((code, column) => { tables[code][cells[0]] = cells[column + 1] })
  })
}

if (problems) process.exit(1)

for (const app of ['APICtech/frontend', 'apictech-admin']) {
  const dir = path.join(root, app, 'src', 'lang')
  fs.mkdirSync(dir, { recursive: true })
  for (const code of CODES) {
    fs.writeFileSync(path.join(dir, `${code}.js`), `// Generated by tools/lang/build.mjs from the translation tables. Have a native speaker review before public release.\nexport default ${JSON.stringify(tables[code], null, 1)}\n`)
  }
  fs.copyFileSync(path.join(root, 'APICtech/frontend/src/languages.js'), path.join(root, app, 'src', 'languages.js'))
  fs.copyFileSync(path.join(root, 'APICtech/frontend/src/i18n.jsx'), path.join(root, app, 'src', 'i18n.jsx'))
}

console.log(`${rows} phrases x ${CODES.length} languages written`)
